export interface ChangelogEntry {
  date: string;
  items: string[];
}

export const CHANGELOG_DATA: ChangelogEntry[] = [
  {
    date: 'October 4, 2026',
    items: [
      'French Doors with Louvered Shutters are now drawn like the real thing: the door width is the doors themselves (a single leaf, a pair or two pairs of divided-light leaves with lever handles, an astragal, an espagnolette bolt and a threshold), and the louvered shutters are separate panels folded back flat on the outside face of the wall either side of the opening, each with slanted slats, a tilt rod, iron strap hinges and a shutter dog. In Presentation mode the doors open and the shutters stay put.',
      'New Casement Window with Louvered Shutters, the matching window for the shuttered French doors: a pair of divided-light casement sashes filling the opening, with the same louvered shutters on the outside wall face beside it.',
      'Sectional Garage Door (Glazed Top Row) and Steel Personnel Door (Vision Panel) are now properly see-through. The glass used to sit in front of a solid panel, so you saw the panel and not through it; each is now built round its glass.',
      'Presentation effects: Pick focus on model now lands on the surface you actually clicked. It used to be caught by invisible or see-through things in front of the model (selection glow, section planes, glass, site occluders); those are ignored now, and if a click hits nothing solid the panel says so and keeps waiting.',
      'The Guided tour editor has a Play tour button. It plays your stops in the 3D view with the same caption card the client sees (Play / Pause, Back / Next), so you can check the tour before sharing it.',
      'Recessed downlights are now truly recessed: only a flush trim ring and lens show below the ceiling, the can sits above it (inside a ceiling slab), and the light comes from open air just below the lens so nothing shadows it. Their default strength is 40. Roofing a building (the roof buttons and sdk.architecture.roofBuilding) now also adds a ceiling slab under the roof, with its underside at the top of the walls where room lights are placed; Stack Next Story already provides one as its floor slab.',
      'Interior Studio: rooms were outlined by a convex hull, so an L-shaped room claimed its notch outside the walls. Rooms now keep their true outline, which also fixes curtains (and any furniture) being placed on the outside of windows; curtains now hang on the room side of the wall whichever way the wall is drawn.',
      'Interior Studio is wider and tidier, with two tabs: Furnish rooms (shorter descriptions) and a Gallery of every piece with a picture, size and one-click Add that places it in the chosen room using the furnishing rules (chairs go to desks and tables already there).',
      'The Glass Lens is now an on/off icon on the Camera toolbar that stays on while you use any other tool. Its settings appear as a Glass section at the bottom of the Tool Modifiers panel; everything from Refraction down sits in an Advanced section that starts folded.',
      'New Garage / Workshop doors: sectional (panelled and glazed top row), up-and-over canopy, roller shutter, side-hinged carriage doors, industrial sliding door and a steel personnel door. Overhead doors tilt up and in when opened in Presentation and Walk modes, and roller shutters roll up. Sections, panels, lights and leaves follow the width and height.',
      'The door style library has new filters: Interior, Exterior, Patio, Archways, Sliding, Folding and Pairs, beside the design categories.',
      'Bi-Fold, Sliding Glass Patio and French Doors with Louvered Shutters are now built to suit their width: bi-fold leaves of 0.6 to 0.9 m (2 to 8), sliding panels of about 1.2 m (fixed at the back, sliders in front), and French doors as one leaf, a pair or two pairs with shutters and pane grids sized to fit.',
    ],
  },
  {
    date: 'October 3, 2026',
    items: [
      'New Camera Type tool on the Camera toolbar. Switch the main view between Perspective and Orthographic (parallel lines stay parallel, no size change with distance); your viewpoint and framing carry across the switch. Perspective has Wide, Standard, Telephoto and Long lens presets plus a field-of-view slider. One-click Plan, Front, Rear, Left and Right views and four Isometric views (south-east, south-west, north-east, north-west) are framed to fit the whole model. The Perspective chip now reads Orthographic when that is on, and its Plan and Elevation views use the same framing. Walk and Portal Navigation switch back to Perspective while they run, and the Developer SDK\'s camera.setProjection now works.',
      'Beta environment: cloud quality now has an Auto setting (the new default). It starts at Low on phones and Medium elsewhere, steps down when frames stay slow, and tries one level higher after a long smooth stretch; the lab shows what it chose.',
      'Beta environment: with the Beta sky on, the area below the horizon is now a pale ground in the light theme instead of near-black soil that clashed with the editor floor.',
    ],
  },
  {
    date: 'October 2, 2026',
    items: [
      'The glass lens is now a real glass. It refracts light through a curved rim (choose Dome, Squircle, Bowl or Lip, then set the bezel width, thickness and refractive index), splits colours at the edge, has an adjustable specular highlight with its own angle and width, a soft drop shadow, optional tint and edge blur, and squashes and stretches like liquid as you press and drag it. The lens can be a circle or a rounded rectangle / pill. Your look is remembered.',
      'New Glass Lens tool on the Camera toolbar (and in Toolbar Settings > Camera Toolbar Icons). It is the same glass as Presentation mode\'s Glass and shares its settings; the Glass Modifiers panel has every control plus an "Always follow cursor" switch that keeps the lens under the pointer (turn it off to drag the lens instead).',
      'Scatter cushions and pillows are arranged like a real sofa and bed. Sofa cushions stand upright on the seat in each corner, resting against the back cushions and turned slightly in toward the middle. Bed pillows are propped up against the headboard with scatter cushions leaning on them in front, resting on the duvet, and the odd rolled-up fold at the head of the duvet is gone.',
      'Beds are now made with a real cloth simulation: when you relax upholstery and drape, the duvet and the throw are dropped onto the mattress, pillows and frame by a physical cloth solver, so they fold, wrinkle and hang over the sides instead of being shaped by a formula. The result is saved with the model, so it opens identically every time and nothing is simulated when you view it. Live curtains use the same solver: they keep their gathered folds, stop stretching, and wind now acts on the cloth itself, so a breeze into the room billows them while one blowing along them barely does. The scatter cushions on sofas and beds now lean back against the backrest and pillows instead of leaning out.',
      'Interior Studio can now add lighting for each room type ("Add lighting for the room type", on by default). Living rooms get recessed or flush ceiling lights, a floor lamp by the sofa and table lamps on side tables; bedrooms a flush ceiling light, bedside lamps and a reading lamp; kitchens an even grid of downlights plus pendants over the dining table; bathrooms and toilets a ceiling light and a vanity light over each basin (and a downlight in the shower); offices panel lights and a desk lamp at each desk; workshops strip lights (or high-bays in a large room) and a task lamp on the bench. Fixtures are ordinary editable lamps, furnishing the room again replaces them, and a room is capped at 14 lights. Three new fixtures were added for it: Flush Ceiling Light, Vanity Light and Linear LED Batten, which also appear in Auto light and the lamp styles. Developer API: furnishRoom(roomId, preset, { lighting: true }); the MCP furnish_room tool has a lighting option.',
      'Relax upholstery and drape now clearly changes sofas, armchairs and beds. Each soft part is shaped for what it is: seat cushions sink and swell at the sides, back cushions lean back and slump, mattresses dish, and duvets and throws billow, fold and hang over the sides. The strength slider scales the effect. Sofas and beds are rebuilt with legs, rolled arms, separate seat and back cushions, scatter cushions in a contrasting fabric, a throw, and a bed with an upholstered headboard, a duvet, pillows and a throw at the foot. Models are no larger when saved (a sofa is less than half its old size). Existing sofas and beds in saved models keep their old shape until you furnish the room again.',
      'Interior Studio: Living room, Soft furnishings and Minimal are now one Living room that adapts to the room. A tiny or narrow room gets a sofa and a TV unit; a mid-sized room adds a coffee table, a chair and side tables; a large room adds a second seating group, a console and a bookcase. Seating keeps off the wall with the door, the TV goes on the wall the sofa faces and away from windows, and curtains still fit each window. Scripts that ask for soft-furnishings or minimal get the same Living room.',
      'Interior Studio has a new Garage / Workshop room type: workbenches with pegboard and vice, tool chests, steel shelving racks and pillar drills, scaled to the space (a big workshop also gets a free-standing bench). New pieces: side table, TV unit, workbench, tool chest, shelving rack and pillar drill.',
      'Distant grass is less patchy. The tuft layer used to begin only where the far single blades ended, so the middle distance had thin, isolated blades over bare ground colour. Tufts now start where the middle blade ring ends, and the far tufts are packed about twice as close (about 1 m apart for normal lawn, so neighbouring tufts overlap). Taller grass also gets a denser far blade ring. Cost in a 400 m test field: about 2% more triangles for ordinary grass, about 10% more for 0.9 m grass, and no extra draw calls.',
      'Interior Studio has five new room types: Office, Home office, Kitchen, Bathroom and Toilet. Offices seat a chair at each desk, kitchens size a run of base and wall units (with sink, hob and hood) to the wall and add a fridge freezer and, if there is space, a dining table and chairs, and bathrooms and toilets fit a bath, toilet, basin and shower. Anything that does not fit is left out and reported. The new furniture (desk, office chair, bookcase, filing cabinet, kitchen units, fridge, dining table and chair, bath, shower, toilet, basin) can also be added one piece at a time from the Developer API.',
      'Bathroom, toilet and kitchen fixtures follow plumbing rules: they only stand against walls, keep clear space in front (60 cm for a toilet, 90 cm for kitchen units), and cluster next to each other so supply and waste pipes stay short. Each carries its water supply and waste needs for later use.',
    ],
  },
  {
    date: 'September 29, 2026',
    items: [
      'The Developers page has a "Try it live" playground: pick an example (a room with a roof, a row of columns, spiral steps, colours and finishes), edit the script and press Run to see what it builds in a 3D preview with the Console output beside it. Scripts run in an isolated sandbox with no network access and stop after 5 seconds. The examples and all the text are editable in the CMS.',
      'New GPU Profiler (Visualisation > Scene Helpers > GPU Profiler): a small panel showing live frame time, GPU time, draw calls, triangles and textures. Run benchmark orbits the camera once round your model the same way every time, and Record measures whatever you do. Each run gets plain-language findings (GPU-bound, draw-call-bound, uneven pacing), the heaviest objects and textures, and the quality settings in force; Download log saves it as a file so results can be compared before and after a change. GPU timings need Chrome or Edge.',
      'New roofs now start with the Clay Roof Tiles material from the library: a real tile picture with relief at true tile size, drawn on flat roof planes so it stays fast (no 3D tile models). In the Roof panel, "Flat Planes (Fast)" lets you switch between Tile picture and Plain colour; choosing a colour or one of the 3D tile shapes replaces the picture. Roofs already in your models keep their colour.',
      'Found and fixed by testing in a real scene: existing buildings\' roofs drew almost black (the library pictures are dark and the roof used a packed roughness map), so their materials are lifted and simplified; the arrow-key plane square now follows the pointer over empty ground; more dialogs (light styles, terrain bake, share with client, AI tools) trap focus and close with Esc; Auto Street Light places fewer lamps (up to 24) so the scene stays light.',
      'Tidy-up: the modifier palette no longer sits under the Collapse button or repeats the tool name in a chip that got clipped; toolbar buttons have proper names for screen readers; Content Studio shows a load failure once instead of twice and only shows its header close button on phones; the connector\'s set_street_life can place or remove Auto Street Light lamps.',
      'Sun Intensity now runs 0 to 100: 0 is night, 50 is ordinary daylight and 100 is a bright sun that still looks natural. New models start at 40. Models you saved keep the same light (a sun that was 1.0 now reads 50). Scripts still set the sun with sdk.setSunSettings({ intensity }), where 1.0 is ordinary daylight.',
      'Stairs now check where they go. They may touch a wall but not pass through one, and there must be room to step off at the top: the preview turns red with the reason when they clash, an orange patch shows the space at the top that needs to be clear (green when it is), and a click there does nothing until you move or turn them.',
      'Placing a dormer is no longer guesswork. While you place one, green dots on the roof show every spot where a dormer of that size and type fits, its outline follows the pointer (green fits, red doesn\'t) and the status bar says why it can\'t go where you are pointing (off the roof, across a hip or the ridge, no eave below, and so on).',
      'The Roof modifier panel now follows the app\'s own light or dark setting like the other panels (it had been picking up the computer\'s dark mode, which made Replace / Generate Roof, Roof extras and Advanced Trim & Eaves dark on dark or grey on grey). The same fix applies to every panel that uses the dark styles.',
      'Grabbing the move, rotate or scale gizmo no longer counts as a click on whatever is behind it, so moving a light fixture no longer moves the surface it sits on.',
      'Draw upright shapes with the arrow keys: before the first click of Rectangle, Circle, Polygon, Triangle or Arc, Up holds the drawing plane flat, Right holds it square to the red axis, Left square to the green axis and Down square to the edge under the pointer (rest on it first). A coloured square follows the pointer to show the plane; the same arrow or Esc releases it. After the first click the arrows hold a direction as before.',
      'Cars / People / Birds (renamed from "Show moving cars and people while editing"): cars now take bends in smooth curves, slow down for them, turn round at road ends in a half circle, and indicate the way they are turning. Cars slow and stop for people in their way and queue behind each other, and people wait at the kerb for a car that is coming. Two flocks of birds fly over the site: a small flock wheeling about and geese crossing in a V; they go when the option is off.',
      'Auto Street Light (under Street life in WorldView): places Modern LED cutoff lights on main roads (staggered), cobra heads on streets, double-arm cobra heads on wide roads, at realistic spacing and clear of junctions and buildings; some existing houses get a gate light (post-top acorn or Victorian) and solar or bollard path lights. They are ordinary lamps: edit or delete them, or untick to remove them all.',
      'Lighting: Modern LED Cutoff lights are now a 2 m wide area light at intensity 100. A Track Light has all three lights on its model (a Double Cobra has one at each arm), where before only one worked. Auto light can now place track lights, pendants, chandeliers, office panels and high-bays as well as downlights: tick the fixtures you want and they are shared out between the rooms.',
      'Tidied up: "Photorealistic surroundings" (was "Google photorealistic surroundings") and the extra explanatory lines under the Style the buildings, Photorealistic surroundings and Auto light settings are gone.',
      'Floor slabs now rest against the internal face of the walls instead of stopping a few centimetres short. Slabs already in your models that were made the old way are moved out to the wall when the model opens.',
      'Shadows from lights you add (spot, point, projector and directional) are smoother: the stripes and noise on floors are gone, and the sun\'s shadow edge is less grainy.',
      'A sun intensity of 0 now feels like night: the sky, ambient and environment light fade down (with a cool moonlight tint), so lights you place stand out. The default sun is unchanged.',
      'The Section Plane tool has a modifier panel: show or hide the orange plane (it keeps cutting), and choose the colour and opacity of the see-through lines on the cut-away side, down to fully transparent.',
      'Add Material: the tabs (Colour, Upload Texture, My Textures, PBR Materials, AI Generate) no longer get pushed out of view on the PBR Materials tab.',
      'Settings > Toolbars > Edit Toolbar Locations: toolbars can be dragged again, and an empty screen edge shows a labelled drop target while you drag.',
      'Walk Mode: the floor framing under a floor now leaves the opening where a staircase actually is, including when the stair is turned, so you are no longer stopped by joists across the stairwell.',
    ],
  },
  {
    date: 'September 28, 2026',
    items: [
      'WorldView 3D Site: bring a real place into your model, up to 200 m square, from an address, UK postcode or coordinates. The ground arrives as an editable terrain with its real slopes, and the existing buildings as white models at their mapped heights (measured where the map has them, else floors x 3 m, else estimated from the kind of building).',
      'Existing buildings can be selected, re-heighted, deleted and put back. Deleted ones can be shown as see-through ghosts for before-and-after views. The ground can be plain or show the satellite photo.',
      'LiDAR for imported sites: in England (Environment Agency, 1 m) and the Netherlands (AHN, 0.5 m) the ground is now the surveyed ground, and every existing building gets its measured height and a fitted roof (flat, lean-to, gable, hipped or pyramid). The survey is lined up with the map outlines automatically. Buildings the survey shows as open ground are flagged "Check height". In the USA, 3DEP gives 1 m ground. Typing a new height keeps a fitted roof\'s pitch.',
      'Street life for imported sites: cars drive the real roads, on the side of the road the country drives on. Plain white figures walk the footpaths and pavements, a few stand chatting, and people sit on any benches you add. Choose Off, Quiet, Normal or Busy in WorldView or with "Street" in presentation mode. They move in presentations and on the client page, and in the editor if you tick "Show moving cars and people while editing". Draw your own walking or driving routes, for example across a new garden or up a new drive. Phones and tablets show fewer. Scripts use sdk.worldView.setStreetLife, listRoutes, addRoute and removeRoute, and Claude uses the new set_street_life connector tool.',
      'Building downloads keep trying through a brief busy spell on the OpenStreetMap servers instead of giving up.',
      'The imported site is left out of the bill of materials and presentation build-ups, and is saved with the model. Scripts can do all of this through sdk.worldView (importArea, listBuildings, removeBuilding, restoreBuilding, setBuildingHeight, showExisting, setGroundStyle, getSite), and Claude can through the new import_site connector tool.',
      'Better snapping for Line, Arc, Bézier and Poly, which now share one snap: corners, midpoints, the point where edges or guides cross, and any point on an edge or guide (so a line can end exactly on another and split it). Once you are drawing it lines up along the red, green and blue axes, continues an edge you are extending, and lines up with corners you rest on; rest on an edge to draw parallel or perpendicular to it.',
      'Locks that keep snapping: arrow keys hold an axis (Right red, Left green, Up blue; X, Y and Z still work), Down holds parallel then perpendicular to the edge you rested on, Shift keeps the direction showing. Locking no longer turns snapping off - corners and crossings on the locked line still catch.',
      'The Arc tool now draws into the model like a Line, so arcs split lines and close into surfaces. An arc that starts on an edge is tangent to it, and near a corner a pink point rounds the corner with a tangent arc and trims it in one step. Type a bulge, a radius (2r) or a segment count (12s). Poly now snaps in screen pixels instead of fixed distances, and Shift on Poly holds a direction instead of turning snapping off.',
      'Groups and components for drawn shapes: select faces, right-click > Make Group or Make Component. A group moves, copies and tags as one object and doesn\'t stick to what it touches; double-click to edit inside (the rest fades), Esc or Close to finish, Explode to turn it back. Copies of a component share their inside - edit one and all change; Make Unique splits one off. A Components panel lists them, and .skp exports keep them as SketchUp components.',
      'New Section Plane tool: click a wall or floor to slice the model there and see inside, with a solid fill where walls are cut. Drag the plane to slide it, flip it, or keep several and switch between them. Unlike the camera\'s depth clipping it stays put as you orbit, cuts only the model, and is saved with it. Clicks go through the cut-away part, so you can keep drawing inside.',
      'New Follow Me tool (next to Extrude): sweep a flat shape along a path - mouldings, gutters, kerbs, handrails, pipes. Click the shape, then hover the path to see the result as a wireframe, and click. The path can be a run of lines and arcs, or the edge of a face all the way round. Corners are mitred, curves come out smooth, and the result is ordinary drawn geometry you can push/pull, paint and erase.',
      'Section Plane tool now has its own modifier panel (readable header, all your planes, cutting on/off, flip, move) with a tick list of what the cut affects: ground, map overlay, each kind of existing building (for example Existing house, Existing garage) and your own design. The Outliner groups an imported 3D site as 3D Site > Ground and Existing house / Existing garage / and so on. Lighting: Auto light now lives inside Custom Lights (one list of lights, the selected one highlighted), Pick Sun Centre sits above the sun position sliders, and Animate Sun Rotation now runs at the speed you set and no longer stutters. WorldView: the Satellite / 3D Photorealistic preview switch is gone (the map preview is always the flat satellite one; use the Google surroundings option to see Google\'s 3D in the model).',
      'Style the buildings, rethought: existing buildings now get real materials at true scale (brick, render, stone, concrete or metal from the PBR library) with windows and doors generated from their floors and the length of each wall, instead of satellite photos stretched over the roofs. What a building is decides how it is dressed: houses get punched windows and a front door, shops a glazed ground floor, offices ribbon windows (glass curtain walling when tall), towers glass grids, warehouses and factories metal or concrete with high windows and a roller door, churches tall arched windows, greenhouses glazing. Where the map gives a colour or material it wins; roofs take the colour seen from above (tiles, metal or flat). A building you paint keeps its colour.',
      'Materials: the 3D preview now shows textures, height relief and transparency properly (it sits over a chequered backdrop in studio light, and library materials use their real maps), and the Edit Material dialog for library materials has the same live 3D preview. A pencil icon on library materials and your own textures, on the swatches in the Materials panel and beside the Active material, shows that a material can be edited; double-clicking does the same. Your own colours and textures open the Add Material dialog in edit mode (Save changes). Editing opens over what you were doing, so closing or saving takes you straight back to it. WorldView: Google photorealistic surroundings can now also be switched on for the plain map overlay (cut away under the overlay), and the Google layer measures its own height against the ground repeatedly until it settles, showing the adjustment in the panel.',
      'Toolbars: Settings > Toolbars has a new "Edit Toolbar Locations" switch (off by default). While off, the classic toolbars are locked and show no drag grips. Turn it on to show the grips and drag a toolbar onto the top or bottom half of another to stack them in one column (or the left and right half on a top or bottom edge), or onto a strip between columns to give it its own. This removes the empty space under short toolbars. Add Material is now wider with a 3D preview: click the cube icon on any colour, texture or PBR swatch to see it on a sphere or cube, with height maps shown as relief. PBR Settings and Height Map fold away (closed by default), and the Height Map tabs are readable in dark mode.',
      'WorldView "Google as the site": Google\'s photographic ground, trees and buildings show for everything you haven\'t changed. Click a Google building to select its editable copy. Edit, move, repaint, re-height or delete one and Google\'s version is pressed flat where it stood (and where yours now stands) while the editable one takes over; buildings and shapes you draw press Google flat under themselves. Putting a deleted building back returns Google\'s. Google\'s mesh is one surface, so trees and ground beside a building stay, and the flattening is approximate at the edges.',
      'Wall tool: a new "Lock to 90° turns" switch in the Wall modifiers. On (the default) is the old behaviour, right angles unless you hold Shift; off lets walls run at any angle, as if Shift were always held. WorldView: Activate Map Overlay now sits inside Site position, and the Google photorealistic layer can now unpack Google\'s compressed tiles and says in the panel what it is doing (loading, showing, or why it failed).',
      'WorldView 3D Site: two new switches under Look. "Google photorealistic surroundings" shows Google\'s Photorealistic 3D Tiles around the site (needs a Maps key with the Map Tiles API), also in presentations and on the client page, with Google\'s attribution. It is for looking at only: it can\'t be edited, measured, snapped to or exported. Choose "Cut out site" to keep the editable satellite ground and your buildings over the site with Google filling in around it, or "Google ground" to use Google\'s ground with its buildings pressed flat under yours; a slider raises or lowers the layer. "Style the buildings" gives the editable buildings satellite roofs and walls from the map\'s colour or material tags (or the kind of building); a building you paint keeps its own colour.',
      'Extrude (Push/Pull) now works on the solid you already have instead of building a new piece each time. Pulling the top, end or side of a box moves that face and stretches the walls, so ten pushes are still one box with the same six faces. A rectangle drawn on a face grows a bump or cuts a recess and the face it grew from goes. Hold Ctrl when you release to push a copy that stacks a new slab and keeps the divider (for floors), and double-click a face to repeat the last distance (Ctrl for a copy). Pushing a face right through the far side is refused.',
      'New Dimension, Area Label and Leader Label tools (next to the Tape Measure). Dimension: click two points, move out and click to place a proper dimension line with extension lines and end ticks. Area Label: click a drawn face for its area and perimeter, which updates when the face changes. Leader Label: point at something, place the text and type it. All three are saved with the model and can be selected and deleted.',
      'Tape Measure guide lines: click the middle of an edge, a guide or an axis and move away to place a dashed guide parallel to it, or type the exact distance. Line, Rectangle and the other drawing tools snap onto guides and onto the points where two guides cross, so you can lay out a grid and draw from crossing to crossing. Right after placing a guide, type a new distance to move it.',
      'Scene Helpers has a new Guides switch to hide every guide (hidden guides are not snapped to) and a Delete All Guides button. The Tape Measure now also works on empty ground and snaps its measuring points to corners.',
      'Export SKP now saves a real SketchUp file that SketchUp opens directly (it used to save a glTF file with a .skp name). Drawn shapes arrive as SketchUp faces with their holes, each object as a named group, batched trees and timber as shared components, with your colours as named materials.',
      'Fixed Export GLTF and Export STL leaving out everything drawn with Line, Rectangle, Push/Pull and the other drawing tools.',
      'Fixed exported objects landing in the wrong place (further from the origin than in the scene, and turned or scaled twice). Exports now also leave out light markers and tool previews, name the file after your model, and STL files are saved in the smaller binary form.',
    ],
  },
  {
    date: 'September 27, 2026',
    items: [
      'Curved walls now act as one wall: pieces joined end to end (a curve made of short pieces, or pieces in line) are drawn without lines between them, one click selects the whole wall and the paint bucket paints all of it. A wall ends at a real corner (sharper than 30 degrees), so a straight wall flowing into a curve is part of the same wall. Double-click selects a single piece; with the paint bucket, Shift+click paints just the curved (or just the straight) part and Alt+click paints one piece.',
      'Parapet roofs: the roof surface and the parapet are now separate, so each can be painted on its own (existing parapet roofs get a separate surface the next time their settings change). The roof surface is triangulated properly on curved and L-shaped outlines.',
      'Fixed roofs and other double-sided objects showing a line along every triangle (the diagonal lines across parapets and roof surfaces).',
      'Fixed the ground showing through the floor slab and foundation, which happened most along curved walls: the terrain is now cut away inside ground-floor slabs, so neither the ground nor its surface relief can poke through the floor.',
      'Windows and doors on curved walls (walls made of many short pieces, e.g. from a Bézier shape) are now cut cleanly through every piece they cross, instead of only the piece or two nearest their centre.',
      'Walls with doors and windows no longer show stray edge lines: each wall face is now built as one piece with the openings cut out, so lines appear only round the openings, not across the wall above, below or beside them, and no diagonal seams on curved walls.',
      'Logging out of the app now takes you back to the PolyForm homepage.',
      'In the 3D preview on My Designs, a two-finger swipe on a touchpad now pans the view (pinch or a mouse wheel zooms).',
      'Balconies are now shaped with sliders instead of corner handles: Width left and Width right (from the door\'s centre, as seen from outside), Depth and Floor level. On a curved wall the widths are measured along the curve.',
      'Add a level to a balcony: a new piece joined to its front, left or right, at the same level or any height up or down. Each level has its own width, depth, position, support, floor and guarding. Where levels meet at the same height there is no guarding between them; where the height changes, steps are built automatically and the upper level is guarded along the drop except across the steps. A level added to the front of a cantilever or bracket balcony stands on posts. Deleting a balcony removes its levels.',
      'Show All Dimensions now also shows each balcony\'s floor height above the ground below it.',
      'Convert To Wall: the thickness can now be changed in the dialog (the outside face stays where it was drawn), and a new "Also add floor slab and foundation" option (on by default for walls on the ground) adds a 200 mm floor slab in place of the drawn floor, with the walls standing on it, a foundation below and the ground levelled, as the Wall tool does.',
      'Combine now does everything the separate Subtract tool did: pick flat drawn shapes or 3D objects (boxes, pulled-up shapes, imported objects) and Merge, Subtract or Intersect them. The old Subtract tool has been folded into it.',
      'Closing a Bézier shape is easier: the start point catches the cursor from about 12 pixels away at any zoom, and Enter or a double-click closes the shape (Shift+Enter leaves the curve open). Fixed closed Bézier shapes being wrongly refused as crossing themselves.',
      'The profile menu in the app has a PolyForm home link, which opens the homepage in a new tab.',
      'Balconies on curved walls: placed at a door in a curved wall, a balcony now follows the wall either side of the door instead of leaving wedge gaps. Choose per balcony whether its front follows the same curve or runs straight across (at least the set depth from the wall everywhere). Brackets and posts are spaced evenly along the curve.',
      'A balcony whose wall pieces are merged (for example to fit its door) now stays on the merged wall instead of being removed.',
      'Balconies: the Patio / Decking tool has a new Balcony option. Hover a door (or a window) and click: a balcony goes on the outside of the wall, centred on the opening and 600 mm wider each side, with its floor 50 mm below the door sill (a window takes the storey floor). Drag its corners to resize it, or set its depth and floor level in the panel.',
      'Four kinds of balcony: a cantilevered concrete slab (with a drip under the edge), a steel frame on angled brackets fixed to the wall, a steel frame on posts down to the ground, or a Juliet balcony (guarding across the door, no floor). Floors can be tiles, boards or plain concrete; guarding can be glass, metal balusters, timber spindles, metal & cable, or a solid rendered wall with a coping.',
      'A balcony stays on its wall: moving or turning the wall takes the balcony with it, and deleting the wall removes it (undo brings both back).',
      'Balcony guarding is 1,100 mm high by default (adjustable), and the panel gently warns when it is lower than UK guidance for homes, missing, or made of climbable horizontal cables. Spindles and balusters are always spaced under 100 mm apart, on decks too.',
      'My Designs: each design now shows its saved picture, and Preview opens it in 3D right on the page (drag to orbit, right-drag or two fingers to pan, scroll or pinch to zoom) with the same materials and lighting as the editor, before you open it. Nothing is changed or saved by previewing.',
      'Fixed Save As losing drawn surfaces (Rectangle, Circle, Polygon, Poly Line, Bézier, Offset, Push/Pull and Combine results): the new cloud copy now includes them, and Save also stores them together with terrain edits and timber frame settings.',
      'Convert To Wall: right-click a shape drawn with the Rectangle, Circle, Polygon, Bezier, Poly Line or Triangle tools that has been given a wall thickness with Offset (and, optionally, pulled straight up) to turn it into real walls that doors, windows, timber framing and the other architecture tools work with. The option only appears when the shape qualifies: an even-thickness ring lying flat, pulled straight up to a flat, level top, not joined to other geometry and not filled in the middle.',
      'Each edge becomes one wall with exact mitred corners at any angle. Curves keep the pieces they were drawn with, and the dialog reports which pieces are wide enough for a door (1.1 m) or a window (0.7 m) and which suit a decorative wall or column. A flat, unextruded ring asks for a wall height.',
      'Convert To Wall warns about unrealistic thicknesses (under 75 mm, partition-thin, over 500 mm) and heights (under 2.0 m, over a 4 m storey), sharp corners and very short walls. The original shape is replaced; Ctrl+Z brings it back, and the floor inside the ring is kept.',
      'Convert To Wall now also shows greyed out, with the reason, when a shape looks like an attempt at walls but fails a check (for example a ring drawn on an upright face, or one with its middle pulled up too), so the fix is obvious.',
      'Merge Pieces For A Door / Window: right-click a curved wall piece that is too narrow for an opening to merge it with just enough neighbouring pieces into one flat section (centred where you clicked), the way real curved buildings do. The pieces either side still meet it flush, and any door or window already on the merged pieces moves onto the new wall.',
      'Fixed a crash when the wall whose surface was selected is replaced by an edit.',
      'Patio / Decking: draw only the garden side. When both ends of what you have drawn are within 2 m of a building, a fence or garden wall, or another patio, a dashed outline shows how it will close: each loose end runs straight to the wall and the outline follows the building (round corners, and across to a fence where the two meet) back to where you started. Click the wall or press Enter to accept; Tab steps to the other way round. It never wraps round the house.',
      'Patios and decks now tuck 10 mm under walls and fences so no hairline gap can show, and share an exact edge with a neighbouring patio. Edges along a building, fence or patio get no kerb, railing or steps. A patio takes the building floor level, or the level of a patio it joins.',
      'Round buildings are followed with a smooth curved paving edge that stays just under the walls (or piece by piece where the pieces are too coarse for that).',
      'A dragged patio rectangle now moves its near side onto a parallel wall or fence within 2 m. A new patio that overlaps an existing one is trimmed back to share its edge.',
      'Snap To Building: right-click an existing patio or deck to pull edges drawn a little short of (or past) a wall, fence or patio onto it, closing old gaps.',
      'Patio snapping now keeps the same feel at any zoom (about 12 pixels on screen, never more than 350 mm), and snaps to fences and other patios as well as walls.',
      'Fixed patio edges stopping short of the corner on rooms with mitred corners, which left a wedge-shaped gap against the house.',
      'Patio / Decking: when the two ends are near two things that do not meet (a fence stopping short of the house, two separate buildings), the outline now closes with a straight edge across between them.',
      'Snap To Building is now also a button in the Patio panel when a patio or deck is selected.',
      'Parapet roofs no longer show the Advanced Trim & Eaves settings: a parapet roof has no eaves or fascia, so they had no effect.',
      'Undo now covers everything: Ctrl+Z and redo step back through drawn shapes (Rectangle, Circle, Polygon, Poly Line, Bézier), Offset, Push/Pull, delete, paint, hide, duplicate and Divide Surface, in the order you did them, alongside everything else. A drawn shape is one undo step, not one per side.',
      'Offset never folds a shape over itself: edges that vanish on tight curves are collapsed, corners that would spike out more than twice the offset are cut flat, and a narrow neck that pinches closed keeps the larger piece. The preview turns red when the offset is larger than the shape allows.',
      'Poly Line and closed Bézier shapes are now drawn surfaces like Rectangle and Circle, so Offset, Push/Pull, Convert To Wall and Combine Shapes all work on them.',
      'Convert To Wall also accepts offsets the Offset tool had to clean (collapsed edges on tight curves, cut corners): those spots become small wedge-shaped wall pieces.',
      'Combine Shapes: merge overlapping or touching flat shapes into one, subtract later shapes from the first, or keep only their overlap. Use the new Combine Shapes tool (pick a mode, click the shapes in order, press Enter), or Shift-click shapes and right-click. The first shape leads: Subtract keeps it and the result takes its material. One undo step.',
      'Fixed Shift-click (and similar multi-select) on flat shapes lying on the ground: the click also reached the ground, which cleared the selection.',
      'Parapet roofs: the parapet now lines up with the outer wall face instead of sitting half a wall inside it. New Coping Overhang (0 to 100 mm drip) and Roof Slab Projection (0 to 1.5 m) sliders; with a projection, a 250 mm roof slab cantilevers past the walls with the parapet on its edge and a soffit underneath.',
    ]
  },
  {
    date: 'September 16, 2026',
    items: [
      'Walk Mode: Added a new first-person navigation tool to the Camera toolbar/group, next to Portal Navigation. Click a spot on the floor to start walking with WASD movement, mouse look, jumping, gravity, and automatic step/stair climbing against a capsule collider built from the model\'s architecture and landscape geometry.',
      'Walk Mode collides with walls, windows, steps, staircases, roofs, terrain, fences, railings and other solid architecture/landscape shapes (doors remain walk-through), and stops you at an invisible wall around the edge of the model.',
      'Walk Mode pauses (rather than exits) if you lose window focus or switch tabs mid-walk, and resumes with a click; pressing Esc deliberately exits back to your previous tool at the position you walked to.',
      'Added Movement Speed and Mouse Sensitivity settings for Walk Mode to the Tool Modifier panel, persisted across sessions.',
      'Added on-screen joystick, drag-to-look, Jump and Exit controls for Walk Mode on touch devices.',
      'Fixed Walk Mode getting stuck on "Preparing Walk Mode..." on models that mix indexed and non-indexed geometry.',
      'Portal Navigation preview: fixed the preview disc/ring jumping to an unrelated point (or disappearing for a frame) while hovering near an edge, thin member, or opening, without adding the lag a first attempt at this introduced - the fix now only kicks in when the cursor itself is essentially still, so real mouse movement is never delayed.',
      'Portal Navigation preview: fixed a further source of viewport stutter while hovering - the tooltip was updating shared state on Viewport\'s large top-level component, re-rendering it on nearly every mouse move; it is now local to the small preview component instead.',
      'Fixed Walk Mode strafe controls being reversed (D moved left, A moved right).',
      'Walk Mode: holding Shift now sprints (1.6x Movement Speed).',
      'Fixed Camera toolbar icons (Portal Navigation, Walk Mode, Reset Camera, Camera Depth Clipping) using a permanently tinted color scheme unlike every other toolbar; they now match.',
      'Added Walk Mode to the "Camera Toolbar Icons" visibility settings list.',
      'Walk Mode now collides with basic shapes, drawn/poly geometry, floor slabs and everything else you model by default, not just a curated list of architecture/landscape types - so anything you draw can be walked into, stood on, or jumped onto. Doors, small plants (bushes), scale-reference figures and dimension annotations remain walk-through. This also fixes being unable to reach an upper floor via a staircase, since the floor slab (generic "poly" geometry) previously wasn\'t collidable at all.',
      'Fixed Walk Mode getting stuck partway up straight/L-shaped/U-shaped staircases (curved ones were unaffected) - the step-up assist now probes straight into whatever is actually blocking it instead of the player\'s raw look direction, so turning your head mid-climb no longer throws it off.',
      'Fixed Walk Mode not colliding with geometry drawn using the kernel-based drawing tools (lines, arcs, rectangles, polygons) - it now collides the same as everything else.',
    ]
  },
  {
    date: 'April 27, 2026',
    items: [
      'Model Visibility Fix: Resolved an issue where existing models were not showing up in the Open Model list by optimizing the default query to remove Firestore-side orderBy index dependencies and fixing missing icon imports.',
      'Firestore Performance: Removed Firestore-side sorting for model lists, shifting to efficient client-side sorting to eliminate the need for complex composite indexes and prevent query failures on legacy data.',
      'UI Stability Code Fix: Resolved a potential crash in the Open Model popup by correctly importing the Loader2 component from Lucide-React and handles fallback icons gracefully.',
      'Firestore Quota Optimization: Implemented aggressive throttling (1fps) for cursor sync, consolidated Firestore listeners, and added a 30s cache for model fetching to prevent "Quota Exceeded" errors.',
      'Collaborative Cursor Scaling: Fixed collaborative cursors to application scale (constant screen-space size) for a consistent experience regardless of camera zoom. Maintained the high-impact 75px width and scaled name-pill badges for maximum visibility.',
    ]
  },
  {
    date: 'April 21, 2026',
    items: [
      'Collaboration Cursor Synchronization: Implemented real-time (10fps) 3D cursor tracking. Users can now see each other\'s cursors moving in 3D space, anchored to the geometry or ground plane. Fixed a field access bug where cursor positions were incorrectly read as arrays.',
      'Hardened Firestore Security: Optimized and hardened `firestore.rules` to resolve persistent "Missing or insufficient permissions" errors for invited guests. Increased robustness of the `isInvited` check by explicitly validating auth token email presence.',
      'Collaboration Workflow Stability: Fixed a critical bug in the presence detection system that would occasionally fail to associate a guest\'s UID with their invitation document, ensuring consistent write access for all collaborators.',
      'Collaboration Sync Fix: Resolved "Missing or insufficient permissions" and network errors during real-time transformations by correcting the presence document naming convention. Both owners and guests now reliably broadcast presence.',
      'Firestore Data Integrity: Implemented a recursion-based `cleanData` utility to strip `undefined` fields before Firestore updates, eliminating schema validation crashes during rapid geometric edits.',
      'Presence Management Optimization: Introduced an automated "Join Model" routine that ensures a persistence document exists in the `collaborations` collection for all active participants.',
      'Auto Orbit Restoration: Fixed the non-functional Auto Orbit feature by correctly wiring the autoRotate props to the OrbitControls component.',
      'Robust Projector Spin: Re-implemented texture rotation for Projector lights. Instead of rotating the texture matrix (which has no effect on shadow-mapped projections), we now dynamically spin the light\'s `up` vector around its aim axis, correctly rolling the projected image.',
      'Note UI Refinement: Optimized the "New Design Note" popup into a 1200px horizontal rectangle with improved typography and spacing, providing a more professional drafting interface.',
      'Note UI Optimization: Redesigned the "New Design Note" popup with an ultra-wide cinematic aspect ratio (**3360px width**) and a 60% reduction in height for a less intrusive placement experience.',
      'Poly Push/Pull Support: Enabled full Push/Pull functionality for Poly surfaces. Users can now extrude height by pulling the caps or scale the entire polygon by pulling its side faces, making it behave consistently with standard primitives.',
      'Surface Interaction Refinement: Updated the SurfaceHighlight logic for polygons to better distinguish between flat (height=0) surfaces and extruded volumes, providing accurate visual feedback during Push/Pull operations.',
      'Metadata UI Stability: Resolved a recurring "args.slice" TypeError in the metadata overlay and Right Panel by implementing comprehensive Array.isArray checks. This ensures that object-based `poly` arguments are handled gracefully in all property inspectors.',
      'Improved Poly Dimensions UI: Added a dedicated height input field for Poly shapes in the metadata overlay, synchronized with the Push/Pull tool for precise dimension management.',
    ]
  },
  {
    date: 'April 20, 2026',
    items: [
      'Ultra-Panoramic Note Popup: Massively expanded the "Add New Note" UI to **2240px** wide, ensuring a truly immersive drafting experience for complex design annotations.',
      'UI Error Resiliency: Implemented a global `ErrorBoundary` for the Right Panel Stack to catch and compartmentalize rendering crashes without affecting the main viewport.',
      'Poly Tool Crash Fix (args.slice): Resolved a critical error in the dimensions UI where `poly` shapes (which use object-based vertices) would cause a TypeError when treated as array-based primitives.',
      'Save/SaveAs Resilience: Increased the storage upload timeout to **30 seconds** and optimized snapshot compression by 40% to prevent "Storage upload timed out" errors during peak network usage.',
      'Framing Optimization: Refined the "Go to Entity" camera behavior to provide a 4m offset, ensuring the modernized Note UI is perfectly framed and contextually visible.',
      'Poly Tool Stability: Fixed a critical crash during surface creation by implementing a triangulation pre-check; the tool now validates geometry before attempting to render, ensuring stability for complex polygon traces.',
      'Enhanced Poly Tool Visibility: Revamped the "Snap logic" UI. When near the first vertex, the entire closing line segment and active segment now highlight in vibrant yellow with increased thickness for significantly better user visibility.',
      'New `sdk.createPoly` Method: Added support for programmatic polygon creation. Developers can now pass world-space vertices to the SDK, which automatically calculates the best-fit plane and orientation for the new shape.',
      'Robust Model Deletion: Replaced browser-native confirmation dialogs with a high-fidelity custom modal in the "Open Model" view. This ensures reliable deletion even in iframe-sandboxed environments.',
      'Improved SKP Compatibility: Upgraded the binary file detection logic to catch UTF-16 and non-standard encoded SKP signatures, providing users with accurate instructions on using the GLTF bridge.',
      'Go to Entity Zoom Optimization: Increased the zoom resolution for the "Go to Entity" feature. Clicking the link on a note now positions the camera so the note occupies approximately 1/4 of the viewport space.',
      'Dynamic State Sync on Delete: Implemented a global state reset that triggers if the user deletes the currently active model from their library, keeping the workspace synchronized with the data store.',
      'UI Menu Refinement: Renamed the Project "Export" menu to "Import / Export" to better represent the inclusion of SKP and GLTF bridge import tools.',
      'Active WorldView SDK Fix: Resolved an issue where `sdk.worldView.importMap` would update location data but fail to activate the map overlay UI; the map now correctly toggles on when called via script or library.',
      'Interactive Asset Bridge: Enhanced `/example-assets.html` with deep SDK integration. Buttons now trigger spatial geometry creation, map overlays, and diagnostic pings, all with synchronized status reports to the UI console.',
      'Global SDK Exposure: The `DeveloperSDK` is now exposed to `window.sdk`, enabling seamless `parent.sdk` calls from embedded iframes for sophisticated third-party integrations.',
      'New `sdk.log` Method: Added a centralized logging path that routes messages from any source (including webviews) directly into the Developer Suite console for unified debugging.',
      'SDK Documentation Refactor: Relocated advanced Scripting API (scene.*) and Webpage Integration examples to the "Full Documentation" suite for a more intuitive developer experience.',
      'Web-to-SDK Bridge Example: Created a live hosted asset library example at `/example-assets.html` demonstrating interactive buttons that trigger scene changes via `parent.sdk`.',
      'Enhanced Documentation Interactivity: Replaced "Try It" with "Try Now" buttons across all API documentation, ensuring code snippets instantly populate the console for immediate testing.',
      'SKP (.skp) Integration: Introduced high-fidelity bridge support for importing and exporting SKP files. The new "Import SKP" and "Export SKP" options are available under the Project > Export sub-menu.',
      'Embedded Webpage SDK: Launched `sdk.openWebpage(url)`, allowing developers to host and open interactive web documentation or asset libraries directly within the PolyForm workspace.',
      'Script Sandbox Enhancement: Injected the `scene` object as an alias for `sdk` in the developer console, aligning the code execution environment with the technical specification.',
      'Scene Management Patch: Fixed a bug where saving a scene would result in duplicate entries in the Scenes panel due to redundant event listeners.',
      'Poly Tool Stabilization: Restored the Poly tool\'s ability to capture clicks in 3D space by adding it to the interaction listener whitelist. Also verified that vertex placement data is correctly streaming to the AI Diagnostic Log.',
      'Save/SaveAs Reliability Fix: Implemented an 8-second timeout for preview image uploads to Firebase Storage. This prevents the "Save Model" process from hanging indefinitely if Storage services are slow or unresponsive, allowing the Firestore document save to proceed even if the preview thumbnail fails.'
    ]
  },
  {
    date: 'April 19, 2026',
    items: [
      'Dockable UI Panels: Introduced docking and undocking functionality for the "Tool Modifiers" and "Project Messaging" popouts, with a prioritized stacking order below the Collaboration panel.',
      'Poly Tool Stabilization: Resolved geometry triangulation issues in the Poly tool and introduced a persistent PolyGeometry component for smoother rendering and interaction.',
      'Large-Scale Beveling: Expanded the radius and chamfer ranges to 250m with 0.5m precision steps, optimized for architectural scale models.',
      'Integrated Diagnostic Logging: Expanded the AI Diagnostic Log to include real-time reporting for Poly tool vertex placement, messaging events, and bevel parameter changes.',
      'Context-Aware Messaging Access: The "Open Project Messaging" button is now hidden on models without collaborators, reducing clutter for solo designing sessions.',
      'Unified Popout Styling: Redesigned the "Tool Modifiers" palette and "Project Messaging" popout with a standardized UI, matching the color palette and typography of the main panels.',
      'Draggable Messaging Interface: Enhanced the messaging popout with smooth drag functionality using Framer Motion, enabling users to reposition it anywhere in the viewport.',
      'R3F Stability Patch: Resolved a critical "Div is not part of the THREE namespace" error by ensuring UI components like "Messaging" are strictly rendered outside the 3D Canvas.',
      'Palette Visibility Restoration: Corrected a regression where the Tool Modifier palette remained off-screen; restored smooth slide-in animations and transition handling.',
      'Draggable Tool Modifiers: The "Tool Modifiers" palette is now moveable, allowing for a more customized workspace layout.',
      'Project Messaging Redesign: Replaced redundant panel-based messaging with a streamlined floating popout system for enhanced real-time collaboration.',
      'Export Menu Overhaul: Consolidated "Export GLTF" and "Export STL" options into a new "Export" sub-menu in the main burger menu for better organization.',
      'Collaborator Cursor Control: Introduced a toggle to show/hide collaborator cursors in the 3D viewport, reducing visual noise during busy sessions.',
      'Enhanced Save Diagnostics: Integrated deep lifecycle logging for the save process into the AI Diagnostic Log, providing real-time visibility into storage and database operations.',
      'Note Placement Optimization: Refined the "Add Note" UI to ensure it stays anchored, fully visible, and at the highest z-index regardless of viewport position.',
      'AI 3D Designer: Launched a new "AI Generate" tool that builds complex 3D structures from natural language prompts using Gemini 3 Flash.',
      'Contact Friction (Resistance Mode): Implemented a new move modifier that causes objects to "stick" momentarily when they first collide, facilitating precise alignment.',
      'Unified Persistence Engine: Updated the save system to ensure all scene entities, including Notes, Custom Lights, and Animations, are saved with the project.'
    ]
  },
  {
    date: 'April 18, 2026',
    items: [
      'Poly Tool Implementation: Released a new tool for custom 3D modeling that allows users to trace convex polygons on either the ground plane or existing geometry faces.',
      'Surface Generation & CSG Compatibility: Automatically generates a flat surface from any valid traced polygon (3+ vertices), immediately compatible with the Push/Pull tool for complex geometry creation.',
      'Intelligent Plane Detection: The tool automatically locks to the world ground or the face of an existing object based on the initial click for seamless sketching.',
      'Polished Sketching UX: Integrated vertex snapping, real-time preview lines (finished segments, active segment, and ghost closing line), and visual feedback for shape completion.',
      'History & Undo Support: Implemented discrete undo steps for each placed vertex (Ctrl+Z) and robust cancellation (Escape) ensuring a fail-safe modeling experience.',
      'Double-Sided Polygon Rendering: Enabled double-sided materials by default for all generated polygons to ensure visibility from any angle in both 2D and extruded forms.',
      'Input Control Architecture v4.0: Standardized all input elements as controlled components and hardened state initialization to eliminate React "uncontrolled to controlled" warnings across the suite.',
      'State Initialization Hardening: Implemented a strict non-undefined initialization policy for all UI-bound state variables, resolving potential flickering and console errors.',
      'Right Panel & Viewport Refinement: Migrated the 3D Warehouse search, Collaboration invite, and Surface Division modal inputs to a robust controlled state architecture.',
      'Spatial Note Refinement: Fixed note placement logic and enabled billboarding so notes always face the camera while maintaining perspective scaling.',
      'Menu Reorganization: Relocated AI Diagnostic Log to the Developer sub-menu and added a direct "Product Spec" link for improved developer workflow.',
      'Consistent Note Styling: Standardized the visual language of spatial notes between placement and persistent states, featuring rounded-2xl cards and deep shadows.',
      'Live Diagnostic Telemetry: Implemented a full-stack live diagnostic logging system with a 250ms buffered flush mechanism that captures telemetry from useFrame loops without impacting 60fps performance.',
      'Projector Light Instrumentation: Added real-time telemetry points inside the ProjectorLight component to track texture loading, video playback states, and rotation deltas for detailed debugging.',
      'AIDiagnosticLog v3.5: Released an enhanced diagnostic panel featuring a draggable UI, real-time category filtering (RENDER, FRAME, TEXTURE, EFFECT, ERROR), and deep JSON inspection.',
      'Diagnostic Accessibility: Introduced a new [DIAG] button in the TopBar and a global "Ctrl+Shift+L" keyboard shortcut for instant access to the live telemetry feed.',
      'Robust Object Transformation: Replaced legacy property lookups with a scene traversal engine (v3.0) to resolve deep-hierarchy selection bugs and implemented matrix update guarding.',
      'Projector UI Optimization: Streamlined the Projector Light UI by focusing on high-quality static and spinning texture projection with frame-safe rotation logic.',
      'Scalable Animations & Effects: Added the ability to scale particle animations (Fire, Confetti, etc.) directly in the Right Panel for better environmental integration.',
      'Refined Map Integration: Updated WorldView map coverage to support a range of 50m to 450m with automated altitude synchronization.',
      'Collaboration Stability: Implemented deep state comparison and intelligent write-backtracking to reduce Firestore quota consumption by over 40% during active sessions.',
      'Sync Status Transparency: Added a live visual indicator (Synced, Syncing, Error) in the Status Bar to monitor the state of the real-time collaboration engine.',
      'AI Reliability Update: Migrated all AI features to "gemini-3-flash-preview" for stabilized analysis and generative model performance.'
    ]
  },
  {
    date: 'April 17, 2026',
    items: [
      'Enhanced Developer Suite: The suite is now fully draggable and includes a collapse/expand toggle for a more flexible workspace.',
      'Improved Save Reliability: Implemented a resilient save system with silent fallback for asset storage, ensuring model data is always persisted to Firestore even if network conditions block snapshot uploads.',
      'Refined Service Worker: Optimized resource proxying to prevent 500 errors during large data transfers to Firebase Storage.',
      'Implemented "Rectangle Input Mode": Click once with the Rectangle tool to enter precise dimensions (X and Z) directly in the Status Bar.',
      'Scaled 3D environment visualization: Infinite grid and axis gizmos are now optimized for navigation at greater distances (starting at 80m).',
      'Refined Camera Settings: Added "Revert Camera" link to reset default position to [80, 80, 80] and streamlined the Settings modal by removing redundant target fields.',
      'Overhauled Developer Suite: Added a new "Spec" tab featuring a complete technical product specification and Product Manager persona documentation.',
      'Tool Safety: Automatic cancellation of Push/Pull and drawing operations when switching tools to prevent unintended edits.',
      'UI Organization: Reordered toolbar icons for improved workflow hierarchy (Primitives, Boolean tools, and Transforms).',
      'Default Workspace: Enhanced default configuration with "Components" and "Styles" panels disabled for a cleaner initial experience.',
      'Replaced "Default Zoom" with configurable "Default Camera Position" settings.',
      'Added a "Set Default" camera capture tool in the Status Bar (active during Zoom) for one-click viewpoint configuration.',
      'Removed "Focus on Map" button from the toolbar, streamlining navigation for a cleaner interface.',
      'Synchronized Move and Rotate tool gizmos with "Entity Info" panel logic for perfect geometric alignment.',
      'Enhanced real-time Zoom magnification feedback in the Status Bar for precise navigation.',
      'Optimized 3D TransformControls to use Euler rotation (X, Y, Z) ensuring mathematical consistency with UI inputs.',
      'Added "Camera & Navigation" SDK methods with documentation and live examples in the Developer Suite.',
      'Fixed structural bug in "Subtraction" operation to correctly handle complex meshes and CSG vertex attributes.',
      'Enhanced Collaboration: Design owners can now revoke collaboration access from previously invited users directly in the Collaboration panel.',
      'Secure Design Sharing: "Generate Invite Link" now produces design-specific links that enforce invitation-only access for secure, private collaboration sessions.',
      'Restored "+ Add New Note" functionality with a new interactive placement flow and text input UI.',
      'Optimized AI Product Specification to only generate on manual build trigger, reducing redundant background compute.',
      'Standardized Worldview altitude offset to 1m default and improved input precision with a dedicated text field.',
      'Implemented persistent user settings (Theme, Units, Grid, Floor, Notes) saved to Firestore.',
      'Automated "AI Product Specification" generation within the Developer Suite.',
      'Integrated volume and tag tracking into the Object Info displays in both TopBar and Viewport.'
    ]
  },
  {
    date: 'April 16, 2026',
    items: [
      'Implemented a full-featured Animations system in the Visualisation panel, supporting Confetti, Fire, Smoke, Sparks, and Magic Aura particle effects.',
      'Added interactive "Click-to-Place" functionality for animation effects with control over density, looping, and playback status.',
      'Resolved critical Firebase Save stability issues, ensuring the "id" field is correctly managed in model documents and improving synchronization logic.',
      'Fixed CORS preflight (OPTIONS) blocking in the service worker, enabling reliable 3D model preview uploads to Firebase Storage.',
      'Refined Visualisation panel layout by reordering Skybox settings to follow Ambient Occlusion and Fog for a more logical UI flow.',
      'Implemented state persistence for animations, ensuring particle effects are correctly saved to and loaded from Firestore.',
      'Added a "Focus on Map" button to the left toolbar when WorldView is active, helping users find the overlay.',
      'Refactored map texture rendering to use more robust asset loading with React Suspense.',
      'Implemented enhanced developer logging for WorldView (activation, status, and loading/error states).',
      'Updated user documentation with step-by-step WorldView troubleshooting guides.',
      'Improved map overlay visibility by adjusting its rendering height and polygon offset.',
      'Implemented editable Position X, Y, Z coordinates in the Object Information section for shapes.',
      'Transformed the Changelog into a comprehensive "Help" system with two tabs: Documentation and Version History.',
      'Created step-by-step user documentation for all core tools (Rectangle, Box, Push-Pull, WorldView).',
      'Added searchable navigation sidebar to documentation for quick feature lookups.',
      'Standardized Help system styling to match the Developer Console (dark theme, technical aesthetic).',
      'Renamed the Main Menu option from "Show Changelog" to "Help".',
      'Relocated the Changelog trigger to the Main Menu (TopBar) for a cleaner workspace.',
      'Refined Changelog UI color scheme to perfectly match the "Open File" and "Developer Suite" aesthetics.',
      'Increased WorldView map overlay size to 2000m x 2000m for broader geographic context.',
      'Optimized 3D map texture update logic to ensure changes in coordinates are reflected immediately.',
      'Improved map rendering depth with polygon offsetting to eliminate visual artifacts/z-fighting.',
      'Added X, Y, Z coordinates to the Object Information display for more precise tracking.',
      'Fixed a bug where the WorldView map overlay was not displaying due to a missing API key in the 3D renderer.',
      'Calibrated the WorldView map overlay to center exactly at the 3D origin (0,0,0) by default.',
      'Implemented a draggable Help and Changelog system accessible via the question mark icon.',
      'Resolved transformation synchronization issues where objects wouldn\'t follow the move/rotate/scale gizmos.',
      'Enhanced Developer SDK with Proxy-based property manipulation for seamless script-to-viewport updates.',
      'Standardized UI across all modals (Save, Settings, AI) to match the "Open Model" design language.',
      'Made WorldView popup draggable and improved its visual integration.'
    ]
  },
  {
    date: 'April 15, 2026',
    items: [
      'Added real-time measurement display in the status bar.',
      'Support for multiple measurement units (mm, cm, m).',
      'New sub-face selection and coloring in the 3D viewport.',
      'Improved map texture loading through use of THREE.TextureLoader with retry logic.',
      'Resolved CORS issues with external assets through service-worker proxy improvements.'
    ]
  }
];
