import { writeFileSync } from 'node:fs';
import { AUTOMATIC_CHECKS, BUILDING_RULES, GENERAL_RULES } from '../src/rules';
import { registerTools } from '../src/tools';
import { MemoryStore } from '../src/store';

/** Writes RULES.md: everything that steers Claude when it builds, in one readable file. Run: npm run rules:export */
const tools: { name: string; title: string; description: string }[] = [];
registerTools({
  registerTool: (name: string, config: { title?: string; description?: string }) => tools.push({ name, title: config.title ?? name, description: config.description ?? '' }),
} as any, { caller: { uid: 'export', email: 'export@example.com' }, store: new MemoryStore() });

const md = `# PolyForm connector: rules for Claude

This file is generated by \`npm run rules:export\` from the code. Edit the rules in \`mcp/src/rules.ts\` (the
standing rules and the list of automatic checks) and in the tool descriptions in \`mcp/src/tools.ts\`, then export again.

## How to propose a change

Write the change as: the rule id (or a new one), the new wording, and **why** (what went wrong, ideally with the model
it happened in). Then it can be added to \`rules.ts\`, covered by a test in \`mcp/test/building.test.ts\`, and shown here.
Prefer a check in code over a sentence when a mistake can be detected: Claude can ignore a sentence but not a refusal.

## 1. General rules (sent to Claude on connecting)

${GENERAL_RULES}

## 2. Building rules (sent to Claude on connecting)

${BUILDING_RULES.map(r => `### ${r.id}. ${r.title}\n\n**Rule:** ${r.rule}\n\n**Why:** ${r.why}\n`).join('\n')}
## 3. Automatic checks (the connector enforces these itself)

| Id | Where | What it checks |
|---|---|---|
${AUTOMATIC_CHECKS.map(c => `| ${c.id} | ${c.where} | ${c.check} |`).join('\n')}

## 4. Tool descriptions (what Claude reads about each tool)

${tools.map(t => `### \`${t.name}\`: ${t.title}\n\n${t.description}\n`).join('\n')}`;

writeFileSync(new URL('../RULES.md', import.meta.url), md);
console.log(`Wrote RULES.md (${BUILDING_RULES.length} building rules, ${AUTOMATIC_CHECKS.length} checks, ${tools.length} tools).`);
