import { writeFileSync } from 'node:fs';
import {
  AUTOMATIC_CHECKS, BUILT_VALIDATION_TOOLS, GENERAL_RULES, PROPOSED_AUTOMATIC_CHECKS, RECOMMENDED_VALIDATION_CAPABILITIES,
  RULE_ENFORCEMENT, RULE_GROUPS, SPATIAL_DEFAULTS, SPATIAL_DEFAULTS_DESCRIPTION, instructionSize,
} from '../src/rules';
import { registerTools } from '../src/tools';
import { MemoryStore } from '../src/store';

/** Writes RULES.md: everything that steers Claude when it builds, in one readable file. Run: npm run rules:export */
const tools: { name: string; title: string; description: string }[] = [];
registerTools({
  registerTool: (name: string, config: { title?: string; description?: string }) => tools.push({ name, title: config.title ?? name, description: config.description ?? '' }),
} as any, { caller: { uid: 'export', email: 'export@example.com' }, store: new MemoryStore() });

const LABEL = { enforced: 'enforced', partial: 'partly checked', advice: 'advice', unchecked: 'UNCHECKED' } as const;
const size = instructionSize();
const ruleCount = RULE_GROUPS.reduce((n, g) => n + g.rules.length, 0);
const cell = (t: string) => t.replace(/\|/g, '\\|').replace(/\n/g, ' ');

const md = `# PolyForm connector: rules for Claude

This file is generated by \`npm run rules:export\` from the code. Edit the rules, defaults and check lists in \`mcp/src/rules.ts\`
and the tool descriptions in \`mcp/src/tools.ts\`, then export again. A test (\`mcp/test/rules.test.ts\`) fails if a rule names a tool that
does not exist or has no enforcement label.

## How to propose a change

Write the change as: the rule id (or a new one), the new wording, and **why** (what went wrong, ideally with the model it happened in).
Prefer a check in code over a sentence when a mistake can be detected: Claude can ignore a sentence but not a refusal.

## Size of what is sent

${ruleCount} rules in ${RULE_GROUPS.length} groups. Sent to Claude on every connection: **${size.sentChars.toLocaleString()} characters (about ${size.approxTokensSent.toLocaleString()} tokens)**,
rule text only. Sending every reason as well would be ${size.withReasonsChars.toLocaleString()} characters (about ${size.approxTokensWithReasons.toLocaleString()} tokens). Tool descriptions are sent as well, separately (section 6).
Token figures are characters divided by four, a rough guide.

## 1. General rules (sent)

${GENERAL_RULES.trim()}

## 2. Spatial design defaults (sent; read by check_layout)

${SPATIAL_DEFAULTS_DESCRIPTION.trim()}

Values in code: \`${JSON.stringify(SPATIAL_DEFAULTS)}\`

## 3. Rules

How far each rule is backed by the connector: **enforced** (a tool refuses, warns or reports it), **partly checked**, **advice** (judgement, no check intended),
**UNCHECKED** (could be checked, nothing does yet; sent to Claude marked [unchecked]).

${RULE_GROUPS.map(g => `### ${g.title}\n\n| Id | Rule | Why | Backing |\n|---|---|---|---|\n${g.rules.map(r => {
  const e = RULE_ENFORCEMENT[r.id];
  return `| ${r.id} | **${cell(r.title)}.** ${cell(r.rule)} | ${cell(r.why)} | ${LABEL[e.level]}${e.by ? `: ${cell(e.by)}` : ''} |`;
}).join('\n')}\n`).join('\n')}
## 4. Automatic checks (the connector does these itself)

| Id | Where | What it checks |
|---|---|---|
${AUTOMATIC_CHECKS.map(c => `| ${c.id} | ${cell(c.where)} | ${cell(c.check)} |`).join('\n')}

Validation tools built: ${BUILT_VALIDATION_TOOLS.map(t => `\`${t}\``).join(', ')}.

## 5. Proposed checks (not built yet)

| Id | Where | What it would check |
|---|---|---|
${PROPOSED_AUTOMATIC_CHECKS.map(c => `| ${c.id} | ${cell(c.where)} | ${cell(c.check)} |`).join('\n')}

Recommended validation tool concepts: ${RECOMMENDED_VALIDATION_CAPABILITIES.map(t => `\`${t}\``).join(', ')}.

## 6. Tool descriptions (what Claude reads about each tool)

${tools.map(t => `### \`${t.name}\`: ${t.title}\n\n${t.description}\n`).join('\n')}`;

writeFileSync(new URL('../RULES.md', import.meta.url), md);
console.log(`Wrote RULES.md (${ruleCount} rules, ${AUTOMATIC_CHECKS.length} checks, ${PROPOSED_AUTOMATIC_CHECKS.length} proposed, ${tools.length} tools; ~${size.approxTokensSent} tokens sent).`);
