/**
 * The complete `sdk` object surface, grouped the way the Developer Console's
 * "Documentation and Spec" tab groups it (by subsystem namespace). Kept in sync by hand with
 * the `SDK` interface in `src/services/developerService.ts` - every signature and grouping here
 * is real, not illustrative.
 */
export interface SdkMethod {
  name: string;
  signature: string;
  returns: string;
  description: string;
}

export interface SdkTag {
  id: string;
  title: string;
  description: string;
  methods: SdkMethod[];
}

const m = (name: string, signature: string, returns: string, description: string): SdkMethod => ({ name, signature, returns, description });

export const SDK_REFERENCE: SdkTag[] = [
  {
    id: 'core', title: 'Core',
    description: 'Primitives, materials, lighting, notes and view control. Available directly on `sdk`, with no namespace prefix.',
    methods: [
      m('createRectangle', 'sdk.createRectangle({ width, height, position? })', 'Shape', 'Create a flat rectangle.'),
      m('createBox', 'sdk.createBox({ width, height, depth, position? })', 'Shape', 'Create a box.'),
      m('createSphere', 'sdk.createSphere({ radius, position? })', 'Shape', 'Create a sphere.'),
      m('createCone', 'sdk.createCone({ radius, height, position? })', 'Shape', 'Create a cone.'),
      m('createPyramid', 'sdk.createPyramid({ radius, height, position? })', 'Shape', 'Create a pyramid.'),
      m('createDonut', 'sdk.createDonut({ radius, tube, position? })', 'Shape', 'Create a torus (donut).'),
      m('createDome', 'sdk.createDome({ radius, position? })', 'Shape', 'Create a dome.'),
      m('createCylinder', 'sdk.createCylinder({ radius, height, radiusTop?, position? })', 'Shape', 'Create a cylinder, optionally tapered into a cone.'),
      m('createPoly', 'sdk.createPoly({ vertices, position? })', 'Shape', 'Create a polygon from world-space points, ready for Extrude.'),
      m('addObject', 'sdk.addObject(type, props)', 'Shape', 'Add a raw shape of any catalog type. Pass props.id to choose its id; an existing object with that id is replaced.'),
      m('updateObject', 'sdk.updateObject(id, changes)', 'void', 'Change some of an object\'s fields by id; a field set to undefined is removed.'),
      m('pushPull', 'sdk.pushPull(shape, amount)', 'Shape', 'Extrude or intrude a shape (the Extrude tool).'),
      m('applyColor', 'sdk.applyColor(shape, color)', 'void', 'Colour a shape.'),
      m('setTag', 'sdk.setTag(shape, key, value)', 'void', 'Set a custom key/value tag on a shape.'),
      m('setName', 'sdk.setName(shape, name)', 'void', 'Rename a shape.'),
      m('getObjectByName', 'sdk.getObjectByName(name)', 'Shape | undefined', 'Find a shape by its name.'),
      m('getSelectedObject', 'sdk.getSelectedObject()', 'Shape | null', 'Get the currently selected shape.'),
      m('select', 'sdk.select(idOrIds)', 'void', 'Select one or more objects by id.'),
      m('deleteObject', 'sdk.deleteObject(id)', 'void', 'Delete an object.'),
      m('saveScene', 'sdk.saveScene(name)', 'void', 'Save the current model.'),
      m('setSkybox', 'sdk.setSkybox(type, blur?, rotation?, intensity?)', 'void', 'Set the sky/environment preset.'),
      m('setFog', 'sdk.setFog(settings)', 'void', 'Configure scene fog.'),
      m('addLight', 'sdk.addLight(lightData)', 'void', 'Add a light to the scene.'),
      m('setBevelType', "sdk.setBevelType(type)", 'void', "Set the default bevel style ('radius' or 'chamfer')."),
      m('setBevel', 'sdk.setBevel(shape, { amount?, type?, segments? })', 'void', "Bevel a shape's edges."),
      m('divideSurface', 'sdk.divideSurface(shapeId, faceIndex, divisions?)', 'void', 'Subdivide a face into a grid.'),
      m('addProjectorLight', 'sdk.addProjectorLight(lightData)', 'void', 'Add a projector light that casts an image or video.'),
      m('performCSG', "sdk.performCSG(targetId, cutterId, operation)", 'void', "Boolean-combine two shapes ('SUBTRACTION', 'UNION' or 'INTERSECTION')."),
      m('deformObject', 'sdk.deformObject(id, { radius, strength, direction })', 'void', 'Sculpt an object with a radial deform brush.'),
      m('addNote', 'sdk.addNote(text, position)', 'void', 'Pin a note to the model.'),
      m('setNoteVisibility', 'sdk.setNoteVisibility(id, visible)', 'void', 'Show or hide a note.'),
      m('toggleAllNotes', 'sdk.toggleAllNotes(visible)', 'void', 'Show or hide every note.'),
      m('addRectLight', 'sdk.addRectLight(color, intensity, position, scale?)', 'void', 'Add a rectangular area light.'),
      m('animateSun', 'sdk.animateSun(cycleSpeed?)', 'void', 'Animate the sun across the sky.'),
      m('toggleFloor', 'sdk.toggleFloor(enabled)', 'void', 'Show or hide the ground floor.'),
      m('toggleGrid', 'sdk.toggleGrid(enabled)', 'void', 'Show or hide the reference grid.'),
      m('setFloor', 'sdk.setFloor(enabled, color?)', 'void', 'Show or hide the ground floor, optionally setting its colour.'),
      m('setGrid', 'sdk.setGrid(enabled)', 'void', 'Show or hide the reference grid.'),
      m('setShadows', 'sdk.setShadows(enabled)', 'void', 'Turn shadows on or off.'),
      m('setAmbientOcclusion', 'sdk.setAmbientOcclusion(enabled)', 'void', 'Turn ambient occlusion on or off.'),
      m('setAxisIndicator', 'sdk.setAxisIndicator(enabled)', 'void', 'Show or hide the axis lines at the origin.'),
      m('setMiniAxisIndicator', 'sdk.setMiniAxisIndicator(enabled)', 'void', 'Show or hide the small axis gizmo in the corner.'),
      m('setSunSettings', 'sdk.setSunSettings({ intensity?, position?, animate?, speed? })', 'void', "Set the sun's brightness and position, and whether it moves across the sky."),
      m('setGraphicsSettings', 'sdk.setGraphicsSettings(settings)', 'void', 'Set the weather layers (rain, snow, clouds, mist) and vegetation wind.'),
      m('setZoom', 'sdk.setZoom(zoom)', 'void', 'Set the camera zoom.'),
      m('resetView', 'sdk.resetView(view)', 'void', "Snap the camera to a standard view ('perspective', 'plan', 'front', 'rear', 'left' or 'right')."),
      m('setCameraDefaults', 'sdk.setCameraDefaults(position, target)', 'void', "Set the camera's home position."),
      m('focusObject', 'sdk.focusObject(id)', 'void', 'Frame an object in the camera.'),
      m('getSyncStatus', 'sdk.getSyncStatus()', "'synced' | 'syncing' | 'error' | 'offline'", 'Get whether the model is synced.'),
      m('getCollaborators', 'sdk.getCollaborators()', 'Collaborator[]', 'List the people active in the model.'),
      m('diagLog', 'sdk.diagLog(category, message, values?)', 'void', 'Write an entry to the AI Diagnostic Log.'),
      m('setContactFriction', 'sdk.setContactFriction(enabled)', 'void', 'Toggle move-contact friction (pauses briefly when two surfaces touch).'),
      m('generateModel', 'sdk.generateModel(prompt)', 'void', 'Trigger AI Generate from a text prompt.'),
      m('openWebpage', 'sdk.openWebpage(url)', 'void', 'Open a URL in a floating window.'),
      m('log', 'sdk.log(message)', 'void', "Print to the console's output panel."),
    ],
  },
  {
    id: 'architecture', title: 'architecture',
    description: 'Walls, rooms, doors, windows, stairs, roofs and timber framing.',
    methods: [
      m('createRoof', 'sdk.architecture.createRoof({ roofType?, width, depth, ridgeHeight?, pitchAngleDeg?, … })', 'Shape', 'Create a parametric roof (gable, hip or parapet flat).'),
      m('updateRoof', 'sdk.architecture.updateRoof(roofId, { height?, eaveOverhang?, fasciaHeight?, tileShape?, … })', 'void', "Update an existing roof's height, overhang, fascia and tiles."),
      m('listRoofs', 'sdk.architecture.listRoofs()', 'Shape[]', 'List every roof in the model.'),
      m('roofBuilding', 'sdk.architecture.roofBuilding({ roofType, pitchAngleDeg?, ridgeHeight?, eaveOverhang?, tileShape?, … })', 'Shape[]', 'Roof the whole building as the Roof buttons do: the main roof on the top storey and a roof on each extension, replacing existing roofs.'),
      m('checkStairPlacement', 'sdk.architecture.checkStairPlacement({ position, rotationY?, width, height, style?, structure? })', 'StairPlacement | null', 'Validate a staircase against the same footprint, obstacle and landing-clearance rules used by the placement tool.'),
      m('createStairs', 'sdk.architecture.createStairs({ style?, width?, height?, length?, numSteps?, … })', 'Shape', 'Create a parametric staircase flight.'),
      m('createScaleFigure', 'sdk.architecture.createScaleFigure({ characterId?, height?, position?, rotation?, name? })', 'Shape', 'Place one of PolyForm’s procedural human scale figures at an exact height and rotation.'),
      m('listScaleFigureCharacters', 'sdk.architecture.listScaleFigureCharacters()', 'ScaleFigureCharacter[]', 'List the available human reference characters and their default proportions.'),
      m('createRailing', 'sdk.architecture.createRailing({ length?, height?, position?, color? })', 'Shape', 'Create a safety railing.'),
      m('createRoom', 'sdk.architecture.createRoom({ width, length, height?, wallThickness?, justification?, story?, slabThickness?, includeFloor?, includeCeiling?, includeFoundation?, … })', '{ roomId, wallShapes, floorShape?, ceilingShape?, foundationShape? }', 'Create a room through the same closed Wall-tool room assembly, including exact mitres, storey tags, slab/foundation and terrain integration.'),
      m('createWall', 'sdk.architecture.createWall({ start?, end?, length?, height?, thickness?, … })', 'Shape', 'Create a single wall.'),
      m('createDoor', 'sdk.architecture.createDoor({ width?, height?, depth?, position?, rotation?, color?, style?, hostWallId?, name? })', 'Shape', 'Create a styled door/archway assembly. style accepts the same architectural door styles used by the Style Library.'),
      m('createWindow', 'sdk.architecture.createWindow({ width?, height?, depth?, position?, rotation?, color?, style?, hostWallId?, name? })', 'Shape', 'Create a styled window assembly using the Style Library window identifiers.'),
      m('setWallTransparency', 'sdk.architecture.setWallTransparency({ overall?, exterior?, interior? })', 'void', 'Set how see-through walls are.'),
      m('generateTimberFraming', 'sdk.architecture.generateTimberFraming({ roofId?, spacing?, rafterWidth?, … })', 'Shape[]', 'Generate studs, plates, headers, noggins, rafters and ridges.'),
      m('clearTimberFraming', 'sdk.architecture.clearTimberFraming()', 'void', 'Remove all generated timber framing.'),
      m('configureRoofDefaults', 'sdk.architecture.configureRoofDefaults(settings)', 'void', 'Set the defaults new roofs are created with.'),
      m('getRoofDefaults', 'sdk.architecture.getRoofDefaults()', 'RoofConfigDefaults', 'Read the current roof defaults.'),
      m('configureStairsDefaults', 'sdk.architecture.configureStairsDefaults(settings)', 'void', 'Set the defaults new stairs are created with.'),
      m('getStairsDefaults', 'sdk.architecture.getStairsDefaults()', 'StairsConfigDefaults', 'Read the current stairs defaults.'),
      m('configureTimberFramingSettings', 'sdk.architecture.configureTimberFramingSettings(settings)', 'void', 'Set the defaults timber framing is generated with.'),
      m('getTimberFramingSettings', 'sdk.architecture.getTimberFramingSettings()', 'TimberFramingConfigDefaults', 'Read the current timber framing defaults.'),
      m('configureWallSettings', 'sdk.architecture.configureWallSettings(settings)', 'void', 'Set the defaults new walls are created with.'),
      m('getWallSettings', 'sdk.architecture.getWallSettings()', 'WallConfigDefaults', 'Read the current wall defaults.'),
      m('setActiveStory', 'sdk.architecture.setActiveStory(story)', 'void', 'Set which storey new geometry is added to.'),
      m('getActiveStory', 'sdk.architecture.getActiveStory()', 'number', 'Read the active storey.'),
      m('configureDoorDefaults', 'sdk.architecture.configureDoorDefaults(settings)', 'void', 'Set the defaults new doors are created with.'),
      m('getDoorDefaults', 'sdk.architecture.getDoorDefaults()', 'DoorConfigDefaults', 'Read the current door defaults.'),
      m('configureWindowDefaults', 'sdk.architecture.configureWindowDefaults(settings)', 'void', 'Set the defaults new windows are created with.'),
      m('getWindowDefaults', 'sdk.architecture.getWindowDefaults()', 'WindowConfigDefaults', 'Read the current window defaults.'),
    ],
  },
  {
    id: 'referencePlans', title: 'referencePlans',
    description: 'Calibrate image/PDF reference plans to real-world scale and add them as locked model underlays.',
    methods: [
      m('calibrate', 'sdk.referencePlans.calibrate({ pixelWidth, pixelHeight }, { pixelA, pixelB, knownDistanceM })', 'ReferencePlanCalibrationResult', 'Convert a known pixel distance into metres-per-pixel and real plan dimensions.'),
      m('add', 'sdk.referencePlans.add(source, calibration, settings?)', 'Shape', 'Add a calibrated reference plan as a locked textured PolyForm shape.'),
    ],
  },
  {
    id: 'externalAssets', title: 'externalAssets',
    description: 'Validate and insert uploaded, generated or externally sourced geometry with provenance metadata.',
    methods: [
      m('validate', 'sdk.externalAssets.validate(input)', 'GeneratedAssetValidation', 'Validate generated/external geometry before insertion, including geometry size and source provenance.'),
      m('add', 'sdk.externalAssets.add(input)', 'Shape', 'Validate and add external/generated geometry as a native PolyForm shape.'),
    ],
  },
  {
    id: 'bim', title: 'bim',
    description: 'IFC metadata, spatial hierarchy and pluggable IFC geometry import.',
    methods: [
      m('parseIfcMetadata', 'sdk.bim.parseIfcMetadata(text)', 'IfcModelSummary', 'Parse IFC STEP metadata, GUIDs, entity types, property sets and spatial relationships.'),
      m('spatialPath', 'sdk.bim.spatialPath(model, stepId)', 'IfcEntitySummary[]', 'Return the IFC spatial hierarchy path for an entity.'),
      m('registerGeometryProvider', 'sdk.bim.registerGeometryProvider(provider)', 'void', 'Register an IFC tessellation provider. Providers receive IFC bytes and return metadata plus geometry elements.'),
      m('listGeometryProviders', 'sdk.bim.listGeometryProviders()', 'string[]', 'List registered IFC geometry provider ids.'),
      m('importGeometry', 'await sdk.bim.importGeometry(providerId, source)', 'Promise<IfcGeometryImport>', 'Import IFC bytes through a registered geometry provider and add the resulting native shapes to the model.'),
    ],
  },
  {
    id: 'reconstruction', title: 'reconstruction',
    description: 'Reference-image/plan reconstruction drafts, review, validation and model-health checks.',
    methods: [
      m('validateDraft', 'sdk.reconstruction.validateDraft(draft)', 'ReconstructionValidation', 'Validate a reconstruction draft before committing it.'),
      m('checkModelHealth', 'sdk.reconstruction.checkModelHealth()', 'ModelHealthReport', 'Check the current model for reconstruction/geometry health warnings and errors.'),
      m('fromImageObservation', 'sdk.reconstruction.fromImageObservation(observation)', 'ReconstructionDraft', 'Convert a calibrated image-recognition observation into a deterministic reconstruction draft.'),
      m('recogniseOrthogonalPlan', 'sdk.reconstruction.recogniseOrthogonalPlan(image, options)', 'ReconstructionDraft', 'Run the same local high-contrast orthogonal floor-plan recogniser used by Reconstruction Studio and return a deterministic draft.'),
      m('registerImageProvider', 'sdk.reconstruction.registerImageProvider(provider)', 'void', 'Register an image reconstruction provider.'),
      m('listImageProviders', 'sdk.reconstruction.listImageProviders()', 'string[]', 'List registered image reconstruction provider ids.'),
      m('reconstructImage', 'await sdk.reconstruction.reconstructImage(providerId, request)', 'Promise<ReconstructionDraft>', 'Run a registered image provider and return a draft for review; this does not commit geometry by itself.'),
      m('reviewDraft', 'sdk.reconstruction.reviewDraft(draft)', 'ReconstructionReview', 'Build the accepted/review/error decision set for a reconstruction draft.'),
      m('applyReview', 'sdk.reconstruction.applyReview(draft, decisions)', 'ReconstructionDraft', 'Apply per-candidate review decisions to a reconstruction draft.'),
      m('commitDraft', 'sdk.reconstruction.commitDraft(draft, { includeFurniture? })', 'ReconstructionCommitResult', 'Commit approved reconstruction geometry into the current model.'),
    ],
  },
  {
    id: 'interiors', title: 'interiors',
    description: 'Native parametric furniture, collision-aware room furnishing and baked soft-body/cloth settling.',
    methods: [
      m('listRooms', 'sdk.interiors.listRooms()', 'SpatialRoom[]', 'List detected enclosed rooms with stable room ids, level, area, perimeter and bounding walls.'),
      m('addFurniture', "sdk.interiors.addFurniture('bed' | 'sofa' | 'cabinet' | 'curtain', options?)", 'Shape', 'Add native parametric interior furniture or a curtain.'),
      m('listCatalog', 'sdk.interiors.listCatalog()', 'InteriorFurnitureCatalogEntry[]', 'List available interior items, defaults, placement rules and simulation support.'),
      m('furnishRoom', "sdk.interiors.furnishRoom(roomId, 'bedroom' | 'living-room' | 'soft-furnishings' | 'storage' | 'minimal')", 'FurnishingPlan', 'Collision-aware furnishing of a detected room using an Interior Studio preset.'),
      m('bakeSimulation', 'sdk.interiors.bakeSimulation(shapeId, strength?)', 'Shape', 'Bake supported soft-body or cloth settling into deterministic saved mesh geometry.'),
    ],
  },
  {
    id: 'landscape', title: 'landscape',
    description: 'Terrain, planting, site furniture, fences, ponds and patios.',
    methods: [
      m('addPlant', 'sdk.landscape.addPlant(speciesId?, { position?, scale?, rotation?, variation?, color? })', 'Shape', 'Plant a tree, shrub or other species from the plant catalog.'),
      m('addSiteFurniture', "sdk.landscape.addSiteFurniture(type, { position?, rotation?, color?, … })", 'Shape', "Add a bench, lamp, fence run, rock or railing ('bench' | 'lamp' | 'fence' | 'rock' | 'railing')."),
      m('createTerrain', 'sdk.landscape.createTerrain({ width, depth, resolution, topography, … })', 'Shape', "Create terrain ('flat', 'rolling', 'ridge' or 'terraced')."),
      m('applyTerrainTexture', 'sdk.landscape.applyTerrainTexture(textureId)', 'void', 'Paint a texture preset onto the terrain.'),
      m('listPlantCatalog', 'sdk.landscape.listPlantCatalog()', 'PlantSpecies[]', 'List the plant species available to addPlant.'),
      m('listTerrainTextures', 'sdk.landscape.listTerrainTextures()', 'LandscapeTexturePreset[]', 'List the terrain texture presets.'),
      m('configureLandscapeDefaults', 'sdk.landscape.configureLandscapeDefaults(settings)', 'void', 'Set landscape-wide defaults.'),
      m('getLandscapeDefaults', 'sdk.landscape.getLandscapeDefaults()', 'LandscapeConfigDefaults', 'Read the current landscape defaults.'),
      m('configureSculptSettings', "sdk.landscape.configureSculptSettings({ mode?, radius?, intensity?, masked? })", 'void', "Set the terrain sculpting brush's mode ('push', 'pull', 'smooth', 'flatten' or 'pinch'), radius and intensity."),
      m('getSculptSettings', 'sdk.landscape.getSculptSettings()', 'object', 'Read the current sculpting brush settings.'),
      m('configureRoadSettings', 'sdk.landscape.configureRoadSettings({ width?, embankment?, roadColor?, curbHeight? })', 'void', 'Set the defaults for the path/road tool.'),
      m('getRoadSettings', 'sdk.landscape.getRoadSettings()', 'object', 'Read the current path/road settings.'),
      m('addFence', 'sdk.landscape.addFence(points, { style?, height?, closed?, color?, finish?, seed? })', 'Shape', 'A fence run through ground points [x, z], as the Fence tool makes one.'),
      m('addPond', "sdk.landscape.addPond(points, { depth?, clarity?, level?, flow?: { mode: 'still' | 'stream', direction?, speed?, turbulence? } })", 'Shape', 'A pond, lake or flowing water body over an outline of ground points [x, z]. Stream flow uses direction [x,z], speed and turbulence while keeping the same water renderer.'),
      m('updatePond', 'sdk.landscape.updatePond(id, { depth?, clarity?, level?, dig?, flow?, name? })', 'void', 'Edit an existing water body, including its level, basin and current settings. Pass flow: null to return to the default still-water profile.'),
      m('addPatio', "sdk.landscape.addPatio(points, { kind?, deckHeight?, level?, bulges?, settings? })", 'Shape', "A patio or deck over ground points [x, z], levelled with the house floor when drawn against a wall ('patio' or 'deck')."),
      m('updatePatio', 'sdk.landscape.updatePatio(id, { level?, name?, settings?, steps? })', 'void', 'Edit an existing patio/deck including paving/decking look, railing, lighting and placed steps.'),
    ],
  },
  {
    id: 'civil', title: 'civil',
    description: 'Civil/site grading modifiers: spline roads, building pads and pad surface detailing.',
    methods: [
      m('list', 'sdk.civil.list()', 'TerrainModifier[]', 'List all road, pad and surface terrain modifiers.'),
      m('addRoad', 'sdk.civil.addRoad({ points, width?, maxGradePercent?, bankingAngle?, profile?, markings?, material?, batterDistance?, name?, enabled? })', 'RoadModifier', 'Add a spline road using the same persisted terrain-modifier model as the Civil road tool.'),
      m('addPad', 'sdk.civil.addPad({ center, primitive?, dimensions?, rotationY?, targetElevation?, batterDistance?, batterProfile?, name?, enabled? })', 'PadModifier', 'Add a rectangular or circular grading/building pad.'),
      m('setPadSurface', "sdk.civil.setPadSurface(padId, { pattern, parkingConfig?, enabled?, name? } | null)", 'void', 'Add, update or remove parking striping/hatch/asphalt/gravel surface detailing on a pad.'),
      m('update', 'sdk.civil.update(id, changes)', 'void', 'Update a road, pad or surface modifier without changing its id/type.'),
      m('remove', 'sdk.civil.remove(id)', 'void', 'Remove a civil modifier. Removing a pad also removes surface modifiers hosted by that pad.'),
      m('clear', 'sdk.civil.clear()', 'void', 'Remove all civil terrain modifiers.'),
    ],
  },
  {
    id: 'materials', title: 'materials',
    description: 'PBR materials and edge-line rendering.',
    methods: [
      m('applyMaterial', 'sdk.materials.applyMaterial(target, material)', 'void', 'Apply a named preset or a PBR material spec (colour, roughness, metalness, texture and normal/roughness/metalness/AO/displacement map URLs) to a shape.'),
      m('setEdgeLines', 'sdk.materials.setEdgeLines({ enabled?, color?, opacity?, thickness? })', 'void', 'Configure the dark edge lines between adjacent faces.'),
      m('listPresets', 'sdk.materials.listPresets()', 'string[]', 'List the available material preset names.'),
      m('configureMaterialDefaults', 'sdk.materials.configureMaterialDefaults(settings)', 'void', 'Set the defaults new materials are created with.'),
      m('getMaterialDefaults', 'sdk.materials.getMaterialDefaults()', 'MaterialConfigDefaults', 'Read the current material defaults.'),
    ],
  },
  {
    id: 'measurement', title: 'measurement',
    description: 'Dimensions, distance and units.',
    methods: [
      m('addDimension', 'sdk.measurement.addDimension(start, end, labelOrOptions?)', 'Shape', 'Add a placed dimension using the same annotation model as the Dimension tool. labelOrOptions may be text, or { text?, offset? }.'),
      m('addAreaLabel', 'sdk.measurement.addAreaLabel(faceId, anchor?, position?)', 'Shape | null', 'Add a live area/perimeter label to a drawn face; it follows the same stored annotation format as the Area Label tool.'),
      m('addLeader', 'sdk.measurement.addLeader(target, anchor, text)', 'Shape', 'Add a leader label with a line from its text anchor to the target point.'),
      m('addGuide', 'sdk.measurement.addGuide(point, direction, distance?, reach?)', 'Shape', 'Add a saved Tape Measure guide line through a point.'),
      m('addProtractor', 'sdk.measurement.addProtractor({ centre, base, normal?, angle, radius? })', 'Shape', 'Place a saved Protractor measurement and angled guide using the same stored format as the Protractor tool.'),
      m('listGuides', 'sdk.measurement.listGuides()', 'Shape[]', 'List Tape Measure and Protractor guide shapes.'),
      m('deleteGuides', 'sdk.measurement.deleteGuides()', 'number', 'Delete all saved guide lines; returns the number removed.'),
      m('measureDistance', 'sdk.measurement.measureDistance(p1, p2)', '{ distance, dx, dy, dz, horizontalRun, rise, pitchDeg, formatted }', 'Measure the distance, run, rise and pitch between two points.'),
      m('setUnit', "sdk.measurement.setUnit(unit)", 'void', "Set the display unit ('m', 'cm' or 'mm')."),
      m('getUnit', 'sdk.measurement.getUnit()', 'string', 'Read the current display unit.'),
      m('configureMeasurementSettings', 'sdk.measurement.configureMeasurementSettings(settings)', 'void', 'Set measurement-wide defaults.'),
      m('getMeasurementSettings', 'sdk.measurement.getMeasurementSettings()', 'MeasurementConfigDefaults', 'Read the current measurement defaults.'),
    ],
  },
  {
    id: 'sections', title: 'sections',
    description: 'Saved section planes: create, activate, move, flip and control what each plane cuts.',
    methods: [
      m('create', 'sdk.sections.create({ point, normal, size?, active?, showPlane?, xrayColor?, xrayOpacity?, exempt?, name? })', 'Shape', 'Create a saved Section Plane. Activating a new plane automatically deactivates the previous active section.'),
      m('list', 'sdk.sections.list()', 'Shape[]', 'List all saved section planes.'),
      m('setActive', 'sdk.sections.setActive(id, active?)', 'void', 'Turn a section cut on or off; only one section is active at a time.'),
      m('move', 'sdk.sections.move(id, distance)', 'void', 'Move a section plane along its normal by a distance in metres.'),
      m('flip', 'sdk.sections.flip(id)', 'void', 'Flip which side of a section plane is kept.'),
      m('setLayerCut', 'sdk.sections.setLayerCut(id, layer, cut)', 'void', 'Choose whether a section cuts a named layer such as design, ground or a site-building layer.'),
      m('update', 'sdk.sections.update(id, { size?, showPlane?, xrayColor?, xrayOpacity?, exempt? })', 'void', 'Update section display and cut-layer settings.'),
      m('remove', 'sdk.sections.remove(id)', 'void', 'Remove a saved section plane.'),
    ],
  },
  {
    id: 'toolbars', title: 'toolbars',
    description: "Build your own toolbars with your own icons (the Developer Extensibility Suite's Custom toolbars).",
    methods: [
      m('create', 'sdk.toolbars.create({ id?, title, position?, orientation?, items?, … })', 'CustomToolbarDef', 'Create a custom toolbar.'),
      m('addButton', 'sdk.toolbars.addButton(toolbarId, item)', 'void', 'Add a button to a custom toolbar.'),
      m('addToBasicToolbar', 'sdk.toolbars.addToBasicToolbar(item)', 'void', "Add a button to the app's own basic toolbar."),
      m('configureToolbar', 'sdk.toolbars.configureToolbar(toolbarId, settings)', 'void', "Update a custom toolbar's settings."),
      m('configureButton', 'sdk.toolbars.configureButton(toolbarId, buttonId, settings)', 'void', "Update a custom toolbar button's settings."),
      m('configureBasicToolbarButton', 'sdk.toolbars.configureBasicToolbarButton(buttonId, settings)', 'void', "Update a basic-toolbar button's settings."),
      m('getToolbar', 'sdk.toolbars.getToolbar(toolbarId)', 'CustomToolbarDef | undefined', 'Look up a custom toolbar by id.'),
      m('getButton', 'sdk.toolbars.getButton(toolbarId, buttonId)', 'CustomToolbarButton | undefined', 'Look up a toolbar button by id.'),
      m('removeButton', 'sdk.toolbars.removeButton(toolbarId, buttonId)', 'void', 'Remove a button from a custom toolbar.'),
      m('removeFromBasicToolbar', 'sdk.toolbars.removeFromBasicToolbar(buttonId)', 'void', 'Remove a button from the basic toolbar.'),
      m('removeToolbar', 'sdk.toolbars.removeToolbar(toolbarId)', 'void', 'Remove a custom toolbar entirely.'),
      m('list', 'sdk.toolbars.list()', 'CustomToolbarDef[]', 'List every custom toolbar.'),
      m('getBasicToolbarButtons', 'sdk.toolbars.getBasicToolbarButtons()', 'CustomToolbarItem[]', 'List the buttons on the basic toolbar.'),
      m('clear', 'sdk.toolbars.clear()', 'void', 'Remove every custom toolbar.'),
    ],
  },
  {
    id: 'selection', title: 'selection',
    description: 'Selecting, grouping and transforming objects.',
    methods: [
      m('select', 'sdk.selection.select(idOrIds)', 'void', 'Select one or more objects.'),
      m('deselectAll', 'sdk.selection.deselectAll()', 'void', 'Clear the selection.'),
      m('getSelected', 'sdk.selection.getSelected()', 'Shape[]', 'List the currently selected shapes.'),
      m('group', 'sdk.selection.group(ids, groupName?)', 'string', 'Group objects together; returns the new group id.'),
      m('ungroup', 'sdk.selection.ungroup(groupIdOrIds)', 'void', 'Ungroup one or more groups.'),
      m('duplicateObject', 'sdk.selection.duplicateObject(id, offset?)', 'Shape | null', 'Duplicate an object, optionally offset.'),
      m('hideObject', 'sdk.selection.hideObject(id, hidden)', 'void', 'Show or hide an object.'),
      m('isolateObject', 'sdk.selection.isolateObject(id)', 'void', 'Hide everything except one object.'),
      m('unhideAll', 'sdk.selection.unhideAll()', 'void', 'Show every hidden object.'),
      m('transformObject', 'sdk.selection.transformObject(id, { position?, rotation?, scale? })', 'void', 'Move, rotate or scale an object.'),
      m('alignObjects', "sdk.selection.alignObjects(ids, axis, alignment)", 'void', "Align objects along an axis ('x' | 'y' | 'z', 'min' | 'center' | 'max')."),
      m('setFilter', "sdk.selection.setFilter(filter)", 'void', "Restrict what clicking selects ('all' | 'shapes' | 'surfaces')."),
      m('setMode', "sdk.selection.setMode(mode)", 'void', "Set the selection tool's drag mode ('lasso' | 'marquee')."),
    ],
  },
  {
    id: 'camera', title: 'camera',
    description: 'Camera projection, views and depth clipping.',
    methods: [
      m('setNavigationMode', "sdk.camera.setNavigationMode('orbit' | 'pan' | 'zoom' | 'look' | 'walk' | 'teleport')", 'void', 'Activate the same camera/navigation mode as the Camera toolbar.'),
      m('configureWalk', 'sdk.camera.configureWalk({ movementSpeed?, mouseSensitivity? })', 'void', 'Set Walk Mode movement speed and mouse sensitivity.'),
      m('getWalkSettings', 'sdk.camera.getWalkSettings()', '{ movementSpeed?, mouseSensitivity? }', 'Read the current Walk Mode controls.'),
      m('setProjection', "sdk.camera.setProjection(mode)", 'void', "Switch between 'perspective' and 'orthographic'."),
      m('resetView', 'sdk.camera.resetView(view)', 'void', 'Snap the camera to a standard view.'),
      m('setDepthClipping', 'sdk.camera.setDepthClipping({ enabled?, near?, far? })', 'void', "Set the camera's near/far clipping planes."),
      m('setAutoOrbit', 'sdk.camera.setAutoOrbit(enabled, speed?)', 'void', 'Turn on automatic orbiting of the camera.'),
      m('focusObject', 'sdk.camera.focusObject(id)', 'void', 'Frame an object in the camera.'),
      m('setCameraDefaults', 'sdk.camera.setCameraDefaults(position, target)', 'void', "Set the camera's home position."),
      m('setZoom', 'sdk.camera.setZoom(zoom)', 'void', 'Set the camera zoom.'),
    ],
  },
  {
    id: 'ai', title: 'ai',
    description: 'AI Generate, AI Renderer and the assistant panel.',
    methods: [
      m('generateModel', 'sdk.ai.generateModel(prompt)', 'void', 'Generate objects from a text description.'),
      m('openRenderer', 'sdk.ai.openRenderer(prompt?, style?)', 'void', 'Open AI Renderer for a high-fidelity render of the viewport.'),
      m('askAssistant', 'sdk.ai.askAssistant(query?)', 'void', 'Open the AI assistant panel with an optional starting question.'),
      m('openPhotoTo3D', 'sdk.ai.openPhotoTo3D()', 'void', 'Open the same Photo to 3D workflow as the AI toolbar.'),
    ],
  },
  {
  {
    id: 'performance', title: 'performance',
    description: 'GPU/frame profiler automation: record, benchmark, compare and export the same runs shown by the in-app GPU Profiler.',
    methods: [
      m('setEnabled', 'sdk.performance.setEnabled(enabled)', 'void', 'Show or hide the GPU Profiler overlay and probe.'),
      m('isEnabled', 'sdk.performance.isEnabled()', 'boolean', 'Read whether the GPU Profiler is enabled.'),
      m('startBenchmark', 'sdk.performance.startBenchmark()', 'void', 'Start the repeatable fly-around benchmark used by the profiler UI.'),
      m('startRecording', 'sdk.performance.startRecording()', 'void', 'Start a freeform performance recording while using the model normally.'),
      m('stop', 'sdk.performance.stop()', 'void', 'Stop and save the active profiler run.'),
      m('cancel', 'sdk.performance.cancel()', 'void', 'Cancel the active profiler run without saving it.'),
      m('getState', 'sdk.performance.getState()', 'PerfState', 'Read live profiler state, current phase and stored runs.'),
      m('listRuns', 'sdk.performance.listRuns()', 'PerfRun[]', 'List saved performance runs.'),
      m('latest', 'sdk.performance.latest()', 'PerfRun | null', 'Return the latest saved profiler run.'),
      m('latestComparison', 'sdk.performance.latestComparison()', 'Profiler comparison | null', 'Compare the latest run with the previous run of the same kind, including comparison cautions.'),
      m('removeRun', 'sdk.performance.removeRun(id)', 'void', 'Remove one stored performance run.'),
      m('clearRuns', 'sdk.performance.clearRuns()', 'void', 'Clear all stored performance runs.'),
      m('toMarkdown', 'sdk.performance.toMarkdown(runOrId?)', 'string | null', 'Format a profiler run as the same readable summary used by the Copy summary action.'),
    ],
  },
    id: 'scene', title: 'scene',
    description: 'Scene export/import, history and stats.',
    methods: [
      m('exportJSON', 'sdk.scene.exportJSON()', 'string', 'Export the whole scene as JSON.'),
      m('importJSON', 'sdk.scene.importJSON(jsonString)', 'void', 'Replace the scene from exported JSON.'),
      m('clearScene', 'sdk.scene.clearScene(confirm?)', 'void', 'Clear the scene.'),
      m('getStats', 'sdk.scene.getStats()', '{ shapeCount, typeCounts, estimatedVertices, memoryEstimateKB, bounds }', 'Get scene statistics.'),
      m('undo', 'sdk.scene.undo()', 'void', 'Step back one change.'),
      m('redo', 'sdk.scene.redo()', 'void', 'Step forward one change.'),
      m('saveScene', 'sdk.scene.saveScene(name)', 'void', 'Save the current model.'),
      m('getShapeGeometry', 'sdk.scene.getShapeGeometry(id)', '{ positions, normals, uvs? } | null', "Read a shape's raw geometry, by id."),
    ],
  },
  {
    id: 'outliner', title: 'outliner',
    description: 'Introspect the grouping and hierarchy the Outliner panel shows.',
    methods: [
      m('list', 'sdk.outliner.list()', '{ id, name, type, tags? }[]', 'List every entry in the Outliner.'),
      m('find', 'sdk.outliner.find(predicate)', '{ id, name, type, tags? } | null', 'Find the first Outliner entry matching a predicate.'),
    ],
  },
  {
    id: 'blockKit', title: 'blockKit',
    description: "PolyForm's built-in LEGO-style stud-block catalog and placement tool.",
    methods: [
      m('list', 'sdk.blockKit.list()', '{ id, label, category }[]', 'List every block part in the catalog.'),
      m('getGeometry', 'sdk.blockKit.getGeometry(partId)', '{ positions, normals, uvs? } | null', "Read a block part's raw geometry."),
      m('place', 'sdk.blockKit.place(partId, color?)', 'void', 'Arm the placement tool for a block part.'),
      m('setPreventOverlap', 'sdk.blockKit.setPreventOverlap(enabled)', 'void', 'Toggle whether placement refuses to overlap an existing block.'),
    ],
  },
  {
    id: 'text', title: 'text',
    description: 'Flat text labels and solid 3D letters, as the Text and 3D Text tools place them.',
    methods: [
      m('add', 'sdk.text.add({ text, position, normal?, towardsViewer?, size?, bold?, align?, color? })', 'Shape', 'Place a flat text label on a surface (default: the ground), reading the right way up from towardsViewer.'),
      m('add3D', 'sdk.text.add3D({ text, position, size?, depth?, normal?, towardsViewer?, … })', 'Shape', 'Place solid 3D letters standing on position, facing the viewer (or out of a wall, given its normal).'),
      m('edit', 'sdk.text.edit(id, { text?, size?, depth?, bold?, align? })', 'void', "Change a text object's words or settings."),
    ],
  },
  {
    id: 'drawing', title: 'drawing',
    description: 'Drawn geometry: lines, arcs and surfaces, and push/pull on their faces. Points are [x, y, z] in metres. Faces are numbered, and the same steps on the same drawing give the same numbers.',
    methods: [
      m('line', 'sdk.drawing.line(from, to)', 'number[]', 'Draw a line (the Line tool). Lines that close a loop make a face.'),
      m('arc', 'sdk.drawing.arc({ centre, radius, sweep, normal?, startAngle?, segments? })', 'number[]', 'Draw an arc (the Arc tool). Angles are in radians; normal defaults to up.'),
      m('surface', 'sdk.drawing.surface(points)', 'number[]', 'Draw a flat surface from its corners (as Rectangle, Circle and Polygon do); returns its face numbers.'),
      m('shape', 'sdk.drawing.shape(points)', 'number[]', 'Draw a closed shape side by side, as Rectangle, Circle and Triangle do; it stays separate from geometry it crosses.'),
      m('bezier', 'sdk.drawing.bezier({ knots, resolution?, normal? })', 'number[]', 'Draw a closed Bézier curve as a surface (the Bézier tool). Each knot is { point, handleIn?, handleOut? }.'),
      m('rectangle', 'sdk.drawing.rectangle({ centre?, width, depth, normal?, rotationDeg? })', 'number[]', 'Draw a rectangular kernel surface on an arbitrary plane.'),
      m('circle', 'sdk.drawing.circle({ centre?, radius, segments?, normal? })', 'number[]', 'Draw a circular kernel surface with configurable segment count and plane normal.'),
      m('polygon', 'sdk.drawing.polygon({ centre?, radius, sides, rotationDeg?, normal? })', 'number[]', 'Draw a regular N-sided kernel surface.'),
      m('triangle', 'sdk.drawing.triangle({ centre?, radius, rotationDeg?, normal? })', 'number[]', 'Draw a triangular kernel surface.'),
      m('pie', 'sdk.drawing.pie({ centre?, radius, startAngleDeg?, sweepDeg, segments?, normal? })', 'number[]', 'Draw a filled pie/sector surface.'),
      m('freehand', 'sdk.drawing.freehand(points, closed?)', 'number[]', 'Create a freehand/open polyline from sampled points, or a closed surface when closed is true.'),
      m('chamfer', 'sdk.drawing.chamfer(faceIds, amount)', '{ ok, reason? }', 'Chamfer the closed kernel solid represented by the selected faces using the same safe-clamped Chamfer tool binding.'),
      m('fillet', 'sdk.drawing.fillet(faceIds, radius)', '{ ok, reason? }', 'Round the selected kernel solid using the same Fillet tool binding, including prism support and safe radius clamping.'),
      m('boolean', "sdk.drawing.boolean(faceIds, 'merge' | 'subtract' | 'intersect')", '{ ok, faces?, reason? }', 'Combine flat drawn shapes with the same kernel boolean engine used by Merge/Subtract/Intersect.'),
      m('followMe', 'sdk.drawing.followMe(profileFaceId, { edgeId } | { faceId } | { points, closed? })', 'boolean', 'Sweep a drawn profile around an edge chain, a face outline, or an explicit path using the same Follow Me commit path as the interactive tool.'),
      m('offset', 'sdk.drawing.offset(faceId, distance)', 'boolean', "Shrink (negative) or grow a face's outline within its own plane (the Offset tool)."),
      m('pushPull', 'sdk.drawing.pushPull(faceId, distance)', 'boolean', 'Extrude a face along its normal (the Push/Pull tool). Negative pushes in.'),
      m('paint', 'sdk.drawing.paint(faceIds, color)', 'void', 'Paint faces a colour.'),
      m('erase', 'sdk.drawing.erase(faceIds)', 'void', 'Delete faces and the edges only they use.'),
      m('listFaces', 'sdk.drawing.listFaces()', '{ id, label, color, hidden, area, holes }[]', 'List every drawn face.'),
      m('applyChanges', 'sdk.drawing.applyChanges(changes)', 'void', 'Apply a recorded change set exactly. The action recorder writes these for drawing steps.'),
    ],
  },
  {
    id: 'worldView', title: 'worldView',
    description: 'Real places: a 3D site (real ground and existing buildings, up to 200 m square), or the flat Google Maps overlay under the model.',
    methods: [
      m('importMap', 'sdk.worldView.importMap({ lat, lng, zoom?, altitude?, radius? })', 'void', 'Lay a map under the model at a location.'),
      m('setLocation', 'sdk.worldView.setLocation(lat, lng)', 'void', 'Move the map to a new location.'),
      m('setRadius', 'sdk.worldView.setRadius(radius)', 'void', 'Set how much ground the map covers.'),
      m('setZoom', 'sdk.worldView.setZoom(zoom)', 'void', 'Set the map zoom level.'),
      m('setAltitude', 'sdk.worldView.setAltitude(altitude)', 'void', 'Set the altitude the map sits at.'),
      m('importArea', 'await sdk.worldView.importArea(place, { size?, groundStyle?, buildings? })', 'Promise<{ lat, lng, address, size, buildings, warnings }>', 'Bring in a real place: its ground as an editable terrain and its existing buildings. place is an address, a UK postcode, "lat, lng" or { lat, lng }; size is 20-200 m (default 100). Replaces the previous site.'),
      m('getSite', 'sdk.worldView.getSite()', '{ lat, lng, size, address, elevation, groundStyle, showRemoved, ... } | null', 'The imported site, if there is one. elevation is the centre\'s height above sea level, which is y = 0 in the model.'),
      m('listBuildings', 'sdk.worldView.listBuildings()', '{ id, name, height, heightSource, roof, heightCheck, kind, position }[]', 'The existing buildings on the site. heightSource is lidar (measured by survey), tagged (given on the map or typed in), levels (floors x 3 m) or estimated. roof is the fitted roof ({ shape, pitch, eave }) or null for flat; heightCheck is true where the survey shows open ground.'),
      m('removeBuilding', 'sdk.worldView.removeBuilding(id)', 'boolean', 'Delete an existing building. It can still be shown as a ghost, or put back.'),
      m('restoreBuilding', 'sdk.worldView.restoreBuilding(id)', 'boolean', 'Put back a building you removed.'),
      m('setBuildingHeight', 'sdk.worldView.setBuildingHeight(id, height)', 'boolean', 'Correct an existing building\'s height, in metres above its lowest ground. A fitted roof moves with it and keeps its pitch.'),
      m('showExisting', 'sdk.worldView.showExisting(show)', 'void', 'Draw removed buildings as see-through ghosts, for before and after.'),
      m('setGroundStyle', "sdk.worldView.setGroundStyle('plain' | 'satellite')", 'void', 'Plain white-model ground, or the satellite picture (needs a Google Maps key).'),
      m('setGoogleContext', "sdk.worldView.setGoogleContext(on, { ground?: 'cutout' | 'google', nudge?: metres })", 'void', "Show Google's Photorealistic 3D Tiles around the site (needs a Maps key with the Map Tiles API). 'cutout' keeps the editable ground over the site; 'google' uses Google's ground and presses its buildings flat under yours."),
      m('styleBuildings', 'sdk.worldView.styleBuildings(on)', 'void', "Colour the site's buildings: roofs from the satellite picture, walls from the map's colour or material."),
      m('setStreetLife', "sdk.worldView.setStreetLife('off' | 'quiet' | 'normal' | 'busy' | { level?, inEditor? })", 'void', 'Moving cars and people on the site: how busy, and whether they also move in the editor (they always do in presentations unless off).'),
      m('autoStreetLights', 'sdk.worldView.autoStreetLights(on)', 'void', 'Add or remove automatically placed road and garden lights for the imported site. Roads/routes must be loaded first.'),
      m('listRoutes', 'sdk.worldView.listRoutes()', 'SiteRoute[]', 'The roads (cars) and paths (people) on the site: the map\'s and any drawn. Points are [x, z] metres.'),
      m('addRoute', "sdk.worldView.addRoute('path' | 'road', [[x, z], ...])", 'string | null', 'A route of your own: a walking path for people or a driving route for cars. Returns its id.'),
      m('removeRoute', 'sdk.worldView.removeRoute(id)', 'boolean', 'Take a route away.'),
    ],
  },
];

export const SDK_METHOD_COUNT = SDK_REFERENCE.reduce((n, tag) => n + tag.methods.length, 0);
