import { describe, it, expect } from 'vitest';
import * as THREE from 'three';
import { bakeTreeAtlas, attachTreeFade, createTreeViewUniforms, updateTreeView, treeCardRaycast } from './treeImpostor';
import { chooseTreeDetail, treeImpostorView } from './treeLod';
import { VegetationBatch } from './VegetationBatch';
import { VegetationWind } from './VegetationWind';
describe('Distant tree representation', () => {
    it('uses cards only in the supported band and restores geometry in steep views', () => {
        expect(chooseTreeDetail(31, 2, true)).toBe(3);
        expect(chooseTreeDetail(32, 3, true)).toBe(2);
        expect(chooseTreeDetail(18, 2, false)).toBe(2);
        const camera = new THREE.PerspectiveCamera();
        camera.position.set(0, 3, 100);
        expect(treeImpostorView(camera, new THREE.Vector3())).toBe(true);
        camera.position.y = 100;
        expect(treeImpostorView(camera, new THREE.Vector3())).toBe(false);
        expect(treeImpostorView(new THREE.OrthographicCamera(), new THREE.Vector3())).toBe(false);
    });
    it('retains atlas hooks when batching and composes the shared primary camera fade and wind', () => {
        const material = new THREE.MeshStandardMaterial();
        material.onBeforeCompile = s => { s.uniforms.atlasSentinel = { value: 17 }; };
        const wind = new VegetationWind(), batch = new VegetationBatch(new THREE.PlaneGeometry(2, 5), material, wind, 1);
        const view = createTreeViewUniforms(), camera = new THREE.PerspectiveCamera(60, 1);
        camera.position.z = 100;
        camera.lookAt(0, 0, 0);
        camera.updateMatrixWorld();
        updateTreeView(view, camera, 720);
        attachTreeFade(batch.mesh.material, view, 5, true);
        const shader = { uniforms: {}, vertexShader: THREE.ShaderLib.standard.vertexShader, fragmentShader: THREE.ShaderLib.standard.fragmentShader };
        batch.mesh.material.onBeforeCompile(shader as any, {} as any);
        expect(shader.uniforms['atlasSentinel'].value).toBe(17);
        expect(shader.uniforms['pfTreeCamera']).toBe(view.pfTreeCamera);
        expect(shader.uniforms['pfWindTime']).toBe(wind.uniforms.pfWindTime);
        batch.dispose();
        material.dispose();
        batch.mesh.geometry.dispose();
    });
    it('keeps azimuth captures in physical target pixels at DPR 2 and restores renderer state', async () => {
        const geometry = new THREE.BoxGeometry(3, 8, 3);
        geometry.translate(0, 4, 0);
        const material = new THREE.MeshStandardMaterial();
        const target = new THREE.WebGLRenderTarget(20, 20);
        let active = target, clear = new THREE.Color('red'), alpha = .8;
        const captures: number[][] = [];
        const renderer = { autoClear: true, toneMapping: THREE.ACESFilmicToneMapping, getContext: () => ({ isContextLost: () => false }), getRenderTarget: () => active, setRenderTarget: t => { active = t; }, getClearAlpha: () => alpha, getClearColor: c => c.copy(clear), setClearColor: (c, a) => { clear.set(c); alpha = a; }, clear: () => { }, render: () => { captures.push(active.viewport.toArray()); } };
        const atlas = await bakeTreeAtlas(renderer as any, [{ geometry, material }]);
        expect(captures).toHaveLength(16);
        expect(captures[0]).toEqual([0, 0, 256, 256]);
        expect(captures[14]).toEqual([768, 256, 256, 256]);
        expect(active).toBe(target);
        expect(alpha).toBe(.8);
        expect(clear.getHexString()).toBe('ff0000');
        expect(renderer.toneMapping).toBe(THREE.ACESFilmicToneMapping);
        expect(renderer.autoClear).toBe(true);
        expect(atlas.height).toBe(8);
        expect(atlas.primitive.geometry.index!.count / 3).toBe(8);
        atlas.dispose();
        geometry.dispose();
        material.dispose();
        target.dispose();
    });
    it('picks shader-facing cards through their crown volume and keeps instance IDs', () => {
        const mesh = new THREE.InstancedMesh(new THREE.PlaneGeometry(4, 8), new THREE.MeshStandardMaterial(), 2);
        mesh.setMatrixAt(0, new THREE.Matrix4().makeTranslation(0, 4, -10));
        mesh.setMatrixAt(1, new THREE.Matrix4().makeTranslation(20, 4, -10));
        mesh.updateMatrixWorld();
        treeCardRaycast(mesh);
        const hits: THREE.Intersection[] = [];
        mesh.raycast(new THREE.Raycaster(new THREE.Vector3(0, 4, 0), new THREE.Vector3(0, 0, -1)), hits);
        expect(hits).toHaveLength(1);
        expect(hits[0].instanceId).toBe(0);
        mesh.geometry.dispose();
        mesh.material.dispose();
        mesh.dispose();
    });
});
