import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUp, ArrowLeft, FileText, Image, Layers, Link, Save, Sparkles, History, Plus, Eye, Upload, Undo2, Globe, Search, X } from 'lucide-react';
import { COPY, applyProposal, newSection, pageNames, pagePaths, proposalValue, validateContent, validateProposal, type CmsPage, type Proposal, type Revision, type Section, type SectionKind, type SiteContent } from './model';
import { loadDraft, publishDraft, saveDraft, uploadImage, watchHistory, watchPublished } from './service';
import { CmsProvider } from './context';
import MarketingPage from './MarketingPage';
import { Header, Footer, ClosingCTA } from '../marketing/shared';
import { useModalA11y } from '../ui/useModalA11y';
import { MEDIA_SLOTS } from './media';
import './cms.css';
import PreviewFrame from './PreviewFrame';

const TABS = [{ id: 'pages', label: 'Pages & sections', icon: Layers }, { id: 'copy', label: 'Website copy', icon: FileText }, { id: 'media', label: 'Images', icon: Image }, { id: 'links', label: 'Navigation', icon: Link }, { id: 'ai', label: 'AI proposals', icon: Sparkles }, { id: 'history', label: 'Version history', icon: History }] as const;
const KINDS: SectionKind[] = ['hero','text','image','features','gallery','faq','cta'];
function download(name: string, value: unknown) { const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function Field({ label, value, onChange, multiline = false, hint }: { label: string; value: string; onChange: (v: string) => void; multiline?: boolean; hint?: string }) {
  return <label className="cms-field"><span>{label}</span>{multiline ? <textarea rows={4} value={value} onChange={e => onChange(e.target.value)} /> : <input value={value} onChange={e => onChange(e.target.value)} />}{hint && <small>{hint}</small>}</label>;
}
function ImageField({ url, alt, onChange, onError }: { url: string; alt: string; onChange: (url: string, alt: string) => void; onError: (s: string) => void }) {
  const [uploading, setUploading] = useState(false);
  const latestChange = useRef(onChange); latestChange.current = onChange;
  return <div className="cms-image-field"><Field label="Image URL" value={url} onChange={v => onChange(v, alt)} hint="HTTPS or a site-relative URL" /><Field label="Alternative text" value={alt} onChange={v => onChange(url, v)} />
    <label className="cms-button"><Upload size={15} />{uploading ? 'Uploading…' : 'Upload image'}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif" disabled={uploading} className="cms-file-input" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; setUploading(true); try { const url = await uploadImage(file); latestChange.current(url, alt); } catch (error) { onError((error as Error).message); } finally { setUploading(false); e.target.value = ''; } }} /></label>
    {url && <img src={url} alt={alt} className="cms-thumb" />}
  </div>;
}
function SectionEditor({ section: s, change, onError }: { section: Section; change: (s: Section) => void; onError: (s: string) => void }) {
  return <div className="cms-card cms-stack"><Field label="Section name" value={s.label} onChange={v => change({ ...s, label: v })} />
    {s.kind === 'native' ? <p className="cms-muted">This section retains its original design. Edit its text in Website copy and its media in Images.</p> : <>
      <Field label="Heading" value={s.heading} onChange={v => change({ ...s, heading: v })} /><Field label="Body" multiline value={s.body} onChange={v => change({ ...s, body: v })} />
      <ImageField url={s.image} alt={s.alt} onChange={(image, alt) => change({ ...s, image, alt })} onError={onError} />
      <div className="cms-grid"><Field label="Button label" value={s.buttonLabel} onChange={v => change({ ...s, buttonLabel: v })} /><Field label="Button destination" value={s.buttonHref} onChange={v => change({ ...s, buttonHref: v })} /></div>
      {['features','gallery','faq'].includes(s.kind) && <><h3>{s.kind === 'faq' ? 'Questions' : 'Items'}</h3>{s.items.map((item, i) => <div className="cms-card cms-stack" key={i}>
        <Field label={s.kind === 'faq' ? 'Question' : 'Title'} value={item.title} onChange={v => change({ ...s, items: s.items.map((x,j) => j === i ? { ...x, title: v } : x) })} />
        <Field label={s.kind === 'faq' ? 'Answer' : 'Description'} multiline value={item.body} onChange={v => change({ ...s, items: s.items.map((x,j) => j === i ? { ...x, body: v } : x) })} />
        {s.kind !== 'faq' && <ImageField url={item.image} alt={item.alt} onError={onError} onChange={(image,alt) => change({ ...s, items: s.items.map((x,j) => j === i ? { ...x,image,alt } : x) })} />}
        <button onClick={() => change({ ...s, items: s.items.filter((_,j) => j !== i) })}>Remove item</button>
      </div>)}<button onClick={() => change({ ...s, items: [...s.items, { title: '', body: '', image: '', alt: '' }] })}><Plus size={15} />Add item</button></>}
    </>}
  </div>;
}
export default function CmsAdmin({ onClose }: { onClose: () => void }) {
  const [content, setContent] = useState<SiteContent | null>(null), [saved, setSaved] = useState('');
  const [revision, setRevision] = useState(0), [liveRevision, setLiveRevision] = useState(0), [liveContent, setLiveContent] = useState<SiteContent | null>(null);
  const [tab, setTab] = useState<typeof TABS[number]['id']>('pages'), [pageId, setPageId] = useState('home'), [sectionId, setSectionId] = useState('');
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [connected, setConnected] = useState(false);
  const [search, setSearch] = useState(''), [group, setGroup] = useState('all'), [fieldLimit, setFieldLimit] = useState(40);
  const [history, setHistory] = useState<Revision[]>([]), [undo, setUndo] = useState<SiteContent[]>([]);
  const [proposal, setProposal] = useState<Proposal | null>(null), [selected, setSelected] = useState<number[]>([]);
  const [preview, setPreview] = useState(false), [mobilePreview, setMobilePreview] = useState(false), [addKind, setAddKind] = useState<SectionKind>('text');
  const workspace = useRef<HTMLElement>(null);
  useEffect(() => { workspace.current?.scrollTo?.(0, 0); }, [tab, preview, pageId]);
  const dirty = !!content && JSON.stringify(content) !== saved;
  const closeState = useRef({ busy, dirty, proposal, onClose });
  closeState.current = { busy, dirty, proposal, onClose };
  const close = useCallback(() => { const state = closeState.current; if (state.busy) return; if (!state.dirty && !state.proposal || window.confirm('Leave the CMS and discard unsaved changes and the current proposal?')) state.onClose(); }, []);
  const dialog = useModalA11y<HTMLDivElement>(true, close);
  const load = async () => { setError(''); setBusy(true); try { const draft = await loadDraft(); setContent(draft.content); setSaved(JSON.stringify(draft.content)); setRevision(draft.revision); setUndo([]); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  useEffect(() => { void load(); const off = watchPublished(r => { setConnected(true); setLiveRevision(r?.revision ?? 0); setLiveContent(r?.content ?? null); }, e => { setConnected(false); setError(e.message); }); const historyOff = watchHistory(setHistory, e => setError(e.message)); return () => { off(); historyOff(); }; }, []);
  useEffect(() => { const warn = (e: BeforeUnloadEvent) => { if (dirty || proposal) { e.preventDefault(); e.returnValue = ''; } }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty, proposal]);
  const edit = (next: SiteContent) => { if (!content || busy) return; setUndo(u => [...u.slice(-19), content]); setContent(next); setNotice(''); };
  const page = content?.pages.find(p => p.id === pageId) ?? content?.pages[0];
  const updatePage = (next: CmsPage) => edit({ ...content!, pages: content!.pages.map(p => p.id === next.id ? next : p) });
  const section = page?.sections.find(s => s.id === sectionId);
  const save = async () => { if (!content) return; setBusy(true); setError(''); try { const next = await saveDraft(content, revision); setRevision(next); setSaved(JSON.stringify(content)); setNotice('Draft saved. The published website is unchanged.'); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } };
  const publish = async () => { setBusy(true); setError(''); try { const next = await publishDraft(revision, liveRevision); setNotice(`Version ${next} published.`); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } };
  const copyFields = Object.entries(COPY).filter(([key, field]) => (group === 'all' || field.groups.includes(group)) && (!search || `${field.value} ${content?.copy[key] ?? ''}`.toLowerCase().includes(search.toLowerCase())));
  const previewProps = { page: pageId in pagePaths ? pageId as 'home' : 'home' as const, go: (id: string) => setPageId(id), onLogin: () => {}, user: null, onOpenDesigns: () => {}, onSignOut: () => {} };
  return <div ref={dialog} className="cms" role="dialog" aria-modal="true" aria-labelledby="cms-title" tabIndex={-1}>
    <header className="cms-topbar"><div className="cms-brand"><span className="cms-brand-icon"><Layers size={22} /></span><div><h1 id="cms-title">PolyForm <span>Content studio</span></h1><p>Marketing website · Administrator</p></div></div>
      <div className="cms-actions"><span className={`cms-status ${dirty ? 'cms-status-dirty' : ''}`}>{dirty ? 'Unsaved changes' : `Draft ${revision} · Live ${liveRevision}`}</span>
        <button disabled={!undo.length || busy} title="Undo last edit" onClick={() => { setContent(undo.at(-1)!); setUndo(u => u.slice(0,-1)); }}><Undo2 size={16} /><span>Undo</span></button>
        <button disabled={!content || busy} onClick={() => setPreview(!preview)}><Eye size={16} />{preview ? 'Edit' : 'Preview'}</button>
        <button disabled={!dirty || busy} onClick={save}><Save size={16} />Save draft</button>
        <button className="cms-primary" disabled={!content || dirty || !revision || busy || !connected || JSON.stringify(content) === JSON.stringify(liveContent)} onClick={publish}><Globe size={16} />Publish</button>
        <button className="cms-close-x" onClick={close} aria-label="Close CMS"><X size={18} /></button>
      </div>
    </header>
    {(error || notice) && (content || !error) && <div className={error ? 'cms-alert' : 'cms-notice'} role={error ? 'alert' : 'status'}>{error || notice}<button aria-label="Dismiss message" onClick={() => {setError('');setNotice('');}}><X size={15} /></button></div>}
    <div className="cms-shell"><aside className="cms-sidebar"><p className="cms-eyebrow">WORKSPACE</p>{TABS.map(t => <button key={t.id} className={tab === t.id && !preview ? 'active' : ''} onClick={() => {setTab(t.id);setPreview(false);}}><t.icon size={18} />{t.label}</button>)}<div className="cms-sidebar-bottom"><p>AI changes arrive as proposals.<br />You control what goes live.</p><button onClick={close}><ArrowLeft size={16} />Back to website</button></div></aside>
      <main ref={workspace} className="cms-workspace" aria-busy={busy}>
        {!content ? <div className="cms-empty"><Layers size={36} /><h2>{busy ? 'Loading your content…' : 'Unable to load content'}</h2><p>{!busy && error ? error : 'CMS access requires the verified administrator account and the CMS database rules.'}</p><button disabled={busy} onClick={load}>Retry</button></div> : preview ? <>
          <div className="cms-page-heading"><div><p className="cms-eyebrow">DRAFT PREVIEW · LINKS AND SIGN-IN DISABLED</p><h2>{pageNames[pageId] ?? page?.title ?? 'New page'}</h2></div><div className="cms-actions"><select aria-label="Preview page" value={pageId} onChange={e => setPageId(e.target.value)}>{content.pages.map(p => <option key={p.id} value={p.id}>{pageNames[p.id] ?? p.title ?? p.path}</option>)}</select><button onClick={() => setMobilePreview(!mobilePreview)}>{mobilePreview ? 'Desktop width' : 'Mobile width'}</button></div></div>
          <PreviewFrame mobile={mobilePreview}><CmsProvider value={content}><Header {...previewProps} /><MarketingPage id={pageId} go={previewProps.go} onLogin={() => {}} /><ClosingCTA page={previewProps.page} onLogin={() => {}} /><Footer {...previewProps} /></CmsProvider></PreviewFrame>
        </> : <>
          <div className="cms-page-heading"><div><p className="cms-eyebrow">WEBSITE MANAGEMENT</p><h2>{TABS.find(t => t.id === tab)?.label}</h2><p>{tab === 'pages' ? 'Build your pages from structured sections. Save privately, then publish when ready.' : tab === 'copy' ? 'Edit the existing website without changing its design. Shared wording updates everywhere it is used.' : tab === 'ai' ? 'Review proposed changes against your current draft. Conflicting edits stay protected.' : 'Changes remain private until you publish the saved draft.'}</p></div><button onClick={() => download('polyform-cms-snapshot.json', { schemaVersion: 1, baseRevision: revision, content, fields: COPY })}><Upload size={16} />Export for AI</button></div>
          {tab === 'pages' && <div className="cms-editor-grid"><div className="cms-card cms-page-list"><div className="cms-row"><h3>Pages <span className="cms-count">{content.pages.length}</span></h3><button aria-label="Add page" onClick={() => { const id = 'page-'+crypto.randomUUID().slice(0,8); edit({ ...content, pages:[...content.pages,{id,path:'/'+id,title:'New page',description:'',hidden:false,sections:[]}] });setPageId(id);setSectionId(''); }}><Plus size={16} /></button></div>{content.pages.map(p => <button className={page?.id === p.id ? 'cms-page active' : 'cms-page'} key={p.id} onClick={() => {setPageId(p.id);setSectionId('');}}><FileText size={18} /><span><strong>{pageNames[p.id] ?? p.title ?? 'Untitled'}</strong><small>{p.path}{p.hidden ? ' · Hidden' : ''}</small></span></button>)}</div>
            {page && <div className="cms-stack"><div className="cms-card cms-stack"><h3>Page settings</h3><div className="cms-grid"><Field label="Page title / SEO title" value={page.title} onChange={v => updatePage({ ...page, title:v })} hint="Leave blank to retain the current title on existing pages." /><Field label="Page address" value={page.path} onChange={v => updatePage({ ...page, path:v })} hint={pagePaths[page.id] ? 'Existing page addresses are preserved.' : 'Example: /about'} /></div><Field label="Search description" value={page.description} multiline onChange={v => updatePage({ ...page, description:v })} /><label className="cms-check"><input type="checkbox" disabled={page.id === 'home'} checked={page.hidden} onChange={e => updatePage({ ...page, hidden:e.target.checked })} />Hide page from visitors</label></div>
              <div className="cms-card cms-stack"><div className="cms-row"><h3>Sections</h3><span className="cms-muted">{page.sections.length} sections</span></div>{page.sections.map((s,i) => <div key={s.id} className={`cms-section-row ${s.hidden ? 'cms-hidden-section' : ''}`}><button className="cms-section-name" onClick={() => setSectionId(s.id === sectionId ? '' : s.id)}><span className="cms-section-number">{String(i+1).padStart(2,'0')}</span><span><strong>{s.label}</strong><small>{s.kind === 'native' ? 'Original layout' : s.kind}{s.hidden ? ' · Hidden' : ''}</small></span></button><div className="cms-actions"><button aria-label={`Move ${s.label} up`} disabled={i === 0} onClick={() => {const sections=[...page.sections];[sections[i-1],sections[i]]=[sections[i],sections[i-1]];updatePage({...page,sections});}}><ArrowUp size={15} /></button><button aria-label={`Move ${s.label} down`} disabled={i === page.sections.length-1} onClick={() => {const sections=[...page.sections];[sections[i+1],sections[i]]=[sections[i],sections[i+1]];updatePage({...page,sections});}}><ArrowDown size={15} /></button><button aria-label={`${s.hidden ? 'Show' : 'Hide'} ${s.label}`} onClick={() => updatePage({...page,sections:page.sections.map(x=>x.id===s.id?{...x,hidden:!x.hidden}:x)})}><Eye size={15} /></button>{s.kind !== 'native' && <button aria-label={`Remove ${s.label}`} onClick={() => updatePage({...page,sections:page.sections.filter(x=>x.id!==s.id)})}><X size={15} /></button>}</div></div>)}<div className="cms-actions"><select aria-label="New section type" value={addKind} onChange={e=>setAddKind(e.target.value as SectionKind)}>{KINDS.map(k=><option key={k}>{k}</option>)}</select><button onClick={()=>{const s=newSection(addKind);updatePage({...page,sections:[...page.sections,s]});setSectionId(s.id);}}><Plus size={16} />Add section</button></div></div>
              {section && <SectionEditor key={section.id} section={section} change={s=>updatePage({...page,sections:page.sections.map(x=>x.id===s.id?s:x)})} onError={setError} />}
            </div>}
          </div>}
          {tab === 'copy' && <><div className="cms-filter"><Search size={18} /><input aria-label="Search website copy" placeholder="Search existing text…" value={search} onChange={e=>{setSearch(e.target.value);setFieldLimit(40);}} /><select aria-label="Filter copy by page" value={group} onChange={e=>{setGroup(e.target.value);setFieldLimit(40);}}><option value="all">All pages and shared content</option>{['Home','Features','BuildWithClaude','Developers','SdkDocs','shared','data','sdkFullReference'].map(g=><option key={g}>{g}</option>)}</select><span>{copyFields.length} fields</span></div><div className="cms-copy-list">{copyFields.slice(0,fieldLimit).map(([key,field])=><div className="cms-card" key={key}><div className="cms-row"><span className="cms-eyebrow">{field.groups.join(' · ')}</span>{key in content.copy && <button onClick={()=>{const copy={...content.copy};delete copy[key];edit({...content,copy});}}>Reset to original</button>}</div><Field label={field.value.length > 95 ? field.value.slice(0,95)+'…' : field.value} value={content.copy[key] ?? field.value} multiline onChange={v=>edit({...content,copy:{...content.copy,[key]:v}})} /><small className="cms-muted">Field {key}</small></div>)}</div>{copyFields.length > fieldLimit && <button onClick={()=>setFieldLimit(v=>v+40)}>Show more fields</button>}</>}
          {tab === 'media' && <div className="cms-copy-list">{MEDIA_SLOTS.map(slot=><div className="cms-card cms-stack" key={slot.key}><h3>{slot.label}</h3><p className="cms-muted">{slot.group} · Leave empty to retain the original visual.</p><ImageField url={content.media[slot.key]?.url ?? ''} alt={content.media[slot.key]?.alt ?? slot.label} onError={setError} onChange={(url,alt)=>edit({...content,media:{...content.media,[slot.key]:{url,alt}}})} /></div>)}</div>}
          {tab === 'links' && <div className="cms-stack"><div className="cms-card"><h3>Existing navigation</h3><label className="cms-check"><input type="checkbox" checked={content.replaceNavigation} onChange={e=>edit({...content,replaceNavigation:e.target.checked})} />Replace the original navigation with the links below</label><p className="cms-muted">Edit existing link labels in Website copy → shared. Keep the original links and add new ones, or replace the navigation to control every marketing link. Account controls remain available.</p><button onClick={()=>{setGroup('shared');setTab('copy');}}>Edit existing labels</button></div>{content.links.map((link,i)=><div key={link.id} className="cms-card cms-grid"><Field label="Link label" value={link.label} onChange={v=>edit({...content,links:content.links.map((l,j)=>i===j?{...l,label:v}:l)})} /><Field label="Destination" value={link.href} onChange={v=>edit({...content,links:content.links.map((l,j)=>i===j?{...l,href:v}:l)})} /><label className="cms-field"><span>Location</span><select value={link.location} onChange={e=>edit({...content,links:content.links.map((l,j)=>i===j?{...l,location:e.target.value as 'header'|'footer'}:l)})}><option value="header">Header</option><option value="footer">Footer</option></select></label><button onClick={()=>edit({...content,links:content.links.filter((_,j)=>j!==i)})}>Remove link</button></div>)}<button onClick={()=>edit({...content,links:[...content.links,{id:crypto.randomUUID(),label:'New link',href:'/',location:'header'}]})}><Plus size={16} />Add navigation link</button></div>}
          {tab === 'ai' && <div className="cms-stack"><div className="cms-card cms-stack"><h3>Bring changes through the draft pipeline</h3><p>Export a snapshot and give it to ChatGPT or Claude Code with the instructions in <code>docs/cms/AI-WORKFLOW.md</code>. Import the returned proposal here. Importing never publishes or overwrites conflicting edits.</p><label className="cms-button"><Upload size={16} />Import proposal JSON<input className="cms-file-input" type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>1000000)throw Error('Proposal must be smaller than 1 MB.');const p:unknown=JSON.parse(await file.text());validateProposal(p);setProposal(p);setSelected(p.changes.map((_,i)=>i).filter(i=>JSON.stringify(proposalValue(content,p.changes[i].path))===JSON.stringify(p.changes[i].before)));setError('');}catch(error){setError((error as Error).message);}finally{e.target.value='';}}} /></label></div>{proposal && <><div className="cms-row"><h3>{proposal.title}</h3><span className="cms-status">Based on draft {proposal.baseRevision} · Current {revision}</span><button onClick={()=>{setProposal(null);setSelected([]);}}>Dismiss proposal</button></div>{proposal.changes.map((change,i)=>{const current=proposalValue(content,change.path),conflict=JSON.stringify(current)!==JSON.stringify(change.before);return <div className="cms-card cms-stack" key={change.path}><label className="cms-check"><input type="checkbox" disabled={conflict} checked={selected.includes(i)} onChange={e=>setSelected(s=>e.target.checked?[...s,i]:s.filter(j=>j!==i))} /><strong>{change.path}</strong>{conflict && <span className="cms-conflict">Conflict — current edit protected</span>}</label><div className="cms-grid"><div><p className="cms-eyebrow">CURRENT DRAFT</p><pre>{typeof current==='string'?current:JSON.stringify(current,null,2)}</pre></div><div><p className="cms-eyebrow">AI PROPOSAL</p><pre>{typeof change.after==='string'?change.after:JSON.stringify(change.after,null,2)}</pre></div></div></div>;})}<button className="cms-primary" disabled={!selected.length} onClick={()=>{try{edit(applyProposal(content,proposal,selected));setProposal(null);setSelected([]);setNotice('Selected changes applied to your unsaved draft. Edit, save and publish when ready.');}catch(e){setError((e as Error).message);}}}>Apply {selected.length} selected changes to draft</button></>}</div>}
          {tab === 'history' && <div className="cms-stack"><div className="cms-card"><h3>Published versions</h3><p className="cms-muted">Restore a version into your draft, inspect it, then save and publish. The latest 30 published versions are shown.</p></div>{history.length===0 && <div className="cms-empty"><History size={32} /><h3>No published versions yet</h3><p>Your first CMS publication creates the first restore point.</p></div>}{history.map(r=><div key={r.revision} className="cms-card cms-row"><div><h3>Version {r.revision}{r.revision===liveRevision?' · Live':''}</h3><p className="cms-muted">{(r.updatedAt as {toDate?:()=>Date})?.toDate?.().toLocaleString() ?? 'Publication recorded'}</p></div><button onClick={()=>{try{validateContent(r.content);edit(structuredClone(r.content));setNotice(`Version ${r.revision} restored to your unsaved draft.`);}catch(e){setError((e as Error).message);}}}>Restore to draft</button></div>)}<button disabled={busy} onClick={()=>{if(!dirty||window.confirm('Discard unsaved changes and reload the saved draft?'))void load();}}>Reload saved draft</button></div>}
        </>}
      </main>
    </div>
  </div>;
}
