// German source messages remain stable compiler diagnostics. This presentation
// adapter owns translation, never the saved model or worker protocol.
export const EN={
 'Split-rail · Konstruktionsdemo':'Split rail · Construction demo','Split-rail / Konstruktionsdemo':'Split rail / Construction demo','Dein Zaunverlauf.':'Your fence, your path.',
 'Zeichnen, prüfen, bearbeiten. Nur geprüfte Konstruktionen ersetzen den bestehenden Zaun.':'Draw, validate, edit. Only validated constructions replace the existing fence.',
 'Bis 65 m. Hybrid: unabhängig gegründeter Übergangspfosten mit Luftfugen, kein historischer Verbindungstyp. Tor: geschlossener Prüfflügel. Keine statische Bemessung.':'Up to 65 m. Hybrid: independently founded transition post with clearance gaps, not a historic joint. Gate: static closed leaf. Not a structural engineering assessment.',
 'Verlauf bearbeiten':'Edit path','Ansicht':'Navigate','Neu zeichnen':'Draw new','Punkte':'Edit points','Zurück':'Undo','Vor':'Redo','Zaun löschen':'Delete fence','Lokal speichern':'Save locally','Laden':'Load','Beispiel':'Reset example','Konstruktion':'Construction','Bauart':'Fence type','Wurmzaun':'Worm fence','Pfosten-Riegel':'Post and rail','Höhe':'Height','Torhöhe':'Gate height','Riegel':'Rails','Feldmaß':'Bay length','Zickzack ±':'Zigzag ±','Pfahlpaare':'Post spacing','Füllung':'Density','Luftig':'Open','Normal':'Medium','Dicht':'Dense','Richtung':'Direction','Ansteigend →':'Rising →','Ansteigend ←':'Rising ←','Bindung':'Binding','Weidenrute':'Withy','Wurzel':'Root','Draht':'Wire','Holzbild':'Wood finish','Verwittert':'Weathered','Eiche':'Oak','Frisch':'Fresh','Flechtenfarbig':'Lichen tint','Tor einfügen':'Add gate','Tor-Zielbreite':'Target gate width','Nach Gefälle':'By gradient','Skigard zuerst':'Skigard first','Übergang bei':'Transition at','Torposition':'Gate position','Grundgefälle':'Base slope','Geländeform':'Terrain shape','Ebene / Hang':'Plane / slope','Kuppe':'Crest','Senke':'Hollow','Quergefälle / Wellen':'Crossfall / waves','Querschnitt':'Section','Spaltholz':'Split timber','Halbholz':'Half round','Kantholz':'Squared','Rundling':'Round','Lagen':'Courses','Sortierung':'Seed','Ansichten':'Views','Entwurf':'Overview','Ecke':'Joint','Ende':'End','Gabel':'Fork','Oben':'Top','Seite':'Side','Untersicht':'Underside','Fern':'Far','Prüfhilfen':'Diagnostics','Kontaktstellen':'Bearing contacts','Flächennormalen':'Face normals','Schatten':'Shadows','Anschlüsse geprüft':'Joints validated','Kein Zaun':'No fence','Nicht übernommen · letzter geprüfter Stand bleibt':'Rejected · previous valid model kept','Zaun-Menü':'Fence menu','Prüfung abbrechen':'Cancel validation','Sprache':'Language','Automatisch':'Automatic',
 'Ansicht drehen und zoomen. „Neu zeichnen“ ersetzt den aktuellen Verlauf erst nach bestandener Prüfung.':'Orbit and zoom. “Draw new” replaces the path only after validation.',
 'Mit gedrückter linker Maustaste zeichnen. Loslassen prüft und übernimmt. Escape bricht ab.':'Hold the left mouse button to draw. Release to validate and apply. Escape cancels.',
 'Gelbe Punkte ziehen. Doppelklick auf die Linie fügt einen Punkt hinzu. Entf entfernt den gewählten Punkt.':'Drag yellow points. Double-click the line to add a point. Delete removes the selected point.',
 'Ziehen: drehen · Mausrad: zoomen · rechte Maustaste: verschieben.':'Drag: orbit · Wheel: zoom · Right mouse: pan.',
 'Mausrad: zoomen · maximal 30 FPS bei Änderungen · im Leerlauf keine Renderframes':'Wheel: zoom · up to 30 FPS when changing · no idle render frames',
 'Zaunansicht: zeichnen, Punkte bearbeiten oder Kamera bewegen':'Fence viewport: draw, edit points or move the camera',
 'Konstruktion wird geprüft. Der bisherige Zaun bleibt sichtbar.':'Validating construction. The previous fence stays visible.',
 'Bearbeitung abgebrochen. Letzter gültiger Stand bleibt erhalten.':'Editing cancelled. The previous valid model is preserved.',
 'Zaun gelöscht. Mit „Zurück“ wiederherstellen.':'Fence deleted. Use Undo to restore.',
 'Dieser Entwurf ist lokal im Browser gespeichert.':'This design is saved locally in this browser.',
 'Lokales Speichern nicht verfügbar.':'Local storage is not available.',
 'Kein lesbarer lokaler Entwurf vorhanden.':'No readable local design found.',
 'JSON exportieren':'Export JSON','JSON laden':'Import JSON','Eigene Renderbeispiele':'Rendered examples','Prozedural erzeugt, keine Referenzfotografie.':'Procedurally rendered, not reference photography.',
 'Kameratour':'Camera tour','Tour starten':'Start tour','Tour stoppen':'Stop tour','Tour · 24 Sekunden':'Tour · 24 seconds','Keine Bewegung ohne Start. Escape oder Eingabe stoppt die Tour.':'No autoplay. Escape or any interaction stops the tour.',
 'Auflagerfläche fehlt':'Missing bearing surface','Lagen oder Gefälle außerhalb des Prüfbereichs.':'Courses or slope are outside the validated range.','Ungültige Konstruktionsknoten.':'Invalid construction nodes.','Ein geschlossener Wechselverband benötigt eine gerade Feldzahl.':'A closed alternating fence needs an even number of bays.',
 'Ungültige Pfadpunkte.':'Invalid path points.','Bearbeitungspunkte liegen zu dicht beieinander.':'Edit points are too close together.','Mindestens 2,3 m Verlauf für ein Zaunfeld zeichnen.':'Draw at least 2.3 m for one fence bay.','Dieser Prüfstand unterstützt bis 65 m pro Zaun.':'This demo supports up to 65 m per fence.','Umkehr im Verlauf: die Kurve weiter ziehen.':'Path reverses: draw a wider curve.','Feld wird zu kurz oder zu lang: Verlauf großzügiger führen.':'Bay too short or too long: widen the path.','Zickzack-Ecke nicht baubar: Kurve weiter ziehen.':'Unbuildable zigzag joint: draw a wider curve.','Zaun kommt sich selbst zu nahe. Schleife öffnen oder vergrößern.':'Fence approaches itself too closely. Open or enlarge the loop.',
 'Unbekannte Bauart.':'Unknown fence type.','Tor und Hybrid-Übergang benötigen einen offenen Verlauf. Einen Punkt am Ende öffnen.':'Gate and hybrid transition require an open path. Open the path at its end.','Mehrere Gefällewechsel: manuellen Hybrid-Übergang wählen.':'Multiple gradient changes: choose a manual hybrid transition.','Beidseits des Übergangs werden mindestens 2,3 m Zaun benötigt. Verlauf verlängern oder Übergang verschieben.':'At least 2.3 m of fence is required on each side. Extend the path or move the transition.','Hybrid-Übergang zu eng oder versetzt. Einen geraderen Übergangsbereich wählen.':'Hybrid transition too tight or offset. Choose a straighter transition area.','Hybrid: zu wenig Raum für den gegründeten Übergangspfosten.':'Hybrid: insufficient space for the founded transition post.',
 'Pfosten-Riegel: Richtungswechsel auf mehrere Felder verteilen.':'Post and rail: distribute the turn over more bays.','Geländesprung benötigt kürzere Pfostenfelder.':'Terrain step requires shorter post bays.','Pfostenfeld zu kurz.':'Post bay too short.','Zapfenprofil nicht sternförmig':'Tenon profile is not star-shaped','Skigard-Verlauf zu eng.':'Skigard path too tight.','Skigard: Pfahlpaar verfehlt ein Holz.':'Skigard: a post pair misses a rail.','Skigard: Krümmung benötigt zu breite Pfahlpaare.':'Skigard: curvature requires excessively wide post pairs.','Skigard-Bindung erreicht das Holz nicht.':'Skigard binding does not reach the rail.','Bauteil ohne Länge':'Zero-length member','Ungültiger Gelände-Snapshot.':'Invalid terrain snapshot.','Zaun liegt außerhalb des Gelände-Snapshots.':'Fence lies outside the terrain snapshot.','Unbekannte Geländeform.':'Unknown terrain shape.','Tor benötigt 0,85–3,8 m freie Breite zwischen seinen Pfosten.':'Gate requires 0.85–3.8 m clear width between posts.','Gespeicherte Einstellungen sind nicht gültig.':'Saved settings are invalid.',
 'Auflager nicht erreichbar':'Bearing surface cannot be reached','Holz schneidet das Gelände':'Timber intersects terrain','Ungültige Holzflächen':'Invalid timber surfaces'
};
const dynamic=[['Letzter gültiger Stand bleibt erhalten.','The previous valid model is preserved.'],['Prüfung fehlgeschlagen:','Validation failed:'],['Prüfung läuft ·','Validating ·'],['Bisheriger Zaun bleibt sichtbar.','Previous fence stays visible.'],['Holzbild geändert, geprüfte Geometrie unverändert.','Wood finish changed; validated geometry unchanged.'],['geschlossen ·','closed ·'],[' m Verlauf',' m path'],[' Bauteile',' members'],[' ms Prüfung',' ms validation'],['Tor frei ','Clear gate '],[' Auflager',' bearings'],[' Durchdringungen',' intersections'],['Kontaktrest','Contact gap'],[' Dreiecke',' triangles'],[' Holzkollisionen',' timber collisions'],[' Kollisionen',' collisions'],[' Netzfehler',' mesh errors'],[' Bodenschnitte',' terrain intersections'],[' fehlende Kontakte',' missing contacts'],['Teilabschnitt nicht baubar:','Unbuildable section:'],['Bodenschnitt ','Terrain intersection '],['Keine freie Stakenstellung an Ecke ','No clear stake position at corner '],['Einstellung außerhalb des Konstruktionsbereichs:','Setting outside the construction range:'],['Unbekannte Einstellung:','Unknown setting:'],['Ungültiger Schalter:','Invalid toggle:'],['Ganzzahl erforderlich:','Integer required:']];
export function resolveLanguage(preference='auto',languages=['en']){return ['de','en'].includes(preference)?preference:(languages.find(l=>/^(de|en)(-|$)/i.test(l))||'en').slice(0,2).toLowerCase();}
const storageKey='split-rail-language-v1';let preference='auto';
if(typeof window!=='undefined'){try{preference=localStorage.getItem(storageKey)||'auto';}catch{}preference=new URL(location.href).searchParams.get('lang')||preference;}
export let language=resolveLanguage(preference,typeof navigator==='undefined'?['en']:navigator.languages);
export function translate(text,lang=language){if(lang==='de')return text;if(EN[text])return EN[text];const suffix=' Letzter gültiger Stand bleibt erhalten.';if(text.endsWith(suffix))return translate(text.slice(0,-suffix.length),lang)+' The previous valid model is preserved.';let result=text;for(const [de,en] of Object.entries(EN).filter(([de])=>de.length>35||['Auflager nicht erreichbar','Holz schneidet das Gelände','Ungültige Holzflächen'].includes(de)).sort((a,b)=>b[0].length-a[0].length))result=result.replaceAll(de,en);for(const [de,en] of dynamic)result=result.replaceAll(de,en);return result.replace(/(\d),(\d\d) m/g,'$1.$2 m').replace(/(\d{1,3}(?:\.\d{3})+) triangles/g,(_,n)=>n.replaceAll('.',',')+' triangles');}
const originals=new WeakMap(),attributes=new WeakMap();
// Explicit refresh after UI updates: no MutationObserver, no idle polling.
export function localizeDOM(root=document.body){
  const walk=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement?.closest('script,style,#language')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});
  for(let node=walk.nextNode();node;node=walk.nextNode()){const prev=originals.get(node),source=prev&&node.nodeValue===prev.translated?prev.source:node.nodeValue,translated=source.replace(/\S[\s\S]*\S|\S/,s=>translate(s));originals.set(node,{source,translated});if(node.nodeValue!==translated)node.nodeValue=translated;}
  for(const el of root.querySelectorAll('[aria-label],[alt],[title]')){let record=attributes.get(el);if(!record){record={};attributes.set(el,record);}for(const key of ['aria-label','alt','title'])if(el.hasAttribute(key)){const prev=record[key],value=el.getAttribute(key),source=prev&&value===prev.translated?prev.source:value,translated=translate(source);record[key]={source,translated};el.setAttribute(key,translated);}}
  document.documentElement.lang=language;document.title=translate('Split-rail · Konstruktionsdemo');
}
export function installLanguageControl(){const el=document.getElementById('language');el.value=['de','en'].includes(preference)?preference:'auto';el.onchange=()=>{preference=el.value;try{localStorage.setItem(storageKey,preference);}catch{}language=resolveLanguage(preference,navigator.languages);localizeDOM();window.dispatchEvent(new Event('fence-language-change'));};localizeDOM();}
